### ISSUE TITLE
Metric Labels Not Showing in Case View

### ISSUE THREAD

**Issue by AdventuresInMalware** [CERT-BDF/TheHive#10]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | Current
| Package Type              | Binary
| Browser type & version    | Chrome

### Problem Description
Metric Labels Not Showing in Case View

### Steps to Reproduce
1. Create new Metric
1. Add to Case
1. Set Metric Value (if you can find it)

**Comment by AdventuresInMalware** [comment]
Metric is now showing following a restart of the service.

**Comment by saadkadhi** [comment]
This is weird. @AdventuresInMalware did you by any chance take a screenshot when the problem occured?

**Comment by AdventuresInMalware** [comment]
I didn't and although it happened several times when I first noticed it I now can't get it to reoccur.  I suspect it may have had something to do with my Chrome Plugins.  Please ignore.

**Comment by megan201296** [comment]
I also noticed this issue and I doubt it's any of my chrome extensions.

**Comment by nadouani** [comment]
This is in fact an issue, it's related to the metrics cache in the client side.

The UI loads the list of available metrics to avoid fetching the list every time we need to display a metric name. The issue is that, the cache is not refreshed when a new metric is created.
