### ISSUE TITLE
Misleading MISP Event Date and Time

### ISSUE THREAD

**Issue by saadkadhi** [CERT-BDF/TheHive#101]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 2.9.2
| Package Type              | Binary
| Browser type & version    | Chrome 55

### Problem Description
The date and time corresponding to a MISP event as shown in TheHive's preview & import pane is misleading as it indicates the date and time it was received by TheHive and not the date and time it was created by its author.

### Possible Solutions
Use the date and time of the event creation instead of the date and time of the event as received by TheHive.

**Comment by nadouani** [comment]
The event date displayed in the MISP section of TheHive is the publish date (the date at which the event has been published via on MISP by the event's owner).

IMHO, displaying the publish date is better than the event's creation date.
