### ISSUE TITLE
Update BuildGuide

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/TheHive#102]
### Request Type
Update

### Problem Description
Hello,

You should change the command present to the url https://github.com/CERT-BDF/TheHive/wiki/Build-Guide#214-installation-of-nodejs . Version 7-8 is no longer available.

Have a good day !

**Comment by sigalpes** [comment]
Hi,

thank you for your report and sorry for the noise.

The documentation should be ok now.

Remi.
