### ISSUE TITLE
Hippocampe Analyzer

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/TheHive#104]
### Request Type
Question

### Problem Description

The analyzer works but it does not return the score

![pb](https://cloud.githubusercontent.com/assets/25320209/22364477/2307a398-e472-11e6-9e79-28af54ea4cf7.PNG)

![capture](https://cloud.githubusercontent.com/assets/25320209/22364568/af4e9f64-e472-11e6-9553-0b7c1c8eab91.PNG)

Thanks for your solution

**Comment by nadouani** [comment]
Hello @bjuditt 

We will introduce a new way integrate the analyzer and their job reports into TheHive in the release 2.10.0, and this issue will be fixed.

Thanks
