### ISSUE TITLE
Open log in new windows

### ISSUE THREAD

**Issue by commiaI** [CERT-BDF/TheHive#108]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)      |  Ubuntu 16.04
| Package Type              | Binary

### Problem Description

Hello everyone ! I just installed the new version of TheHive (Congratulations) and I noticed a small bug: It is no longer possible to open the logs in a new window. When clicking, the logs hide but no sign of a new window. 

Have a good day ;)

**Comment by nadouani** [comment]
Nice catch @commiaI, this is fact a bug introduced by the new case list page. 
That said, as a workaround, you can open the flow (what you call logs) in a new window, from the "My tasks" page.

Thanks
