### ISSUE TITLE
Ability to choose the analyzers to run for new observables

### ISSUE THREAD

**Issue by weichea** [CERT-BDF/TheHive#110]
### Request Type
Feature Request

When new observable is added, provide option to select analyzers that the user wants to run instead of just run all analyzers.

**Comment by weichea** [comment]
Found the function to choose the analyzers under Action drop down. Closing this request.

**Comment by nadouani** [comment]
Hi @weichea,

yes you can select one/a bunch of observables and hit Action > Run Analyzers > Choose analyzers you want to run on the selected observables.

We also planned to add the possibility to select and run analyzers during the observables creation process. (This is a feature to be implemented).

Thanks
