### ISSUE TITLE
Adding Tasks to a Template

### ISSUE THREAD

**Issue by commiaI** [CERT-BDF/TheHive#112]
### Request Type
Feature Request

### Requests 
Hi !

Currently, when opening a case with a case template, it is not possible to add a task during creation. It would be good to be able to do that.

Thank you

![tachetemplate](https://cloud.githubusercontent.com/assets/25172187/22737551/e31166de-ee03-11e6-9553-8e20246f122c.PNG)

**Comment by nadouani** [comment]
Hi @commiaI this is in fact "by design" (I don't really like this expression), you can add tasks during the case creation, only if you don't use a template.

**Comment by commiaI** [comment]
Yes precisely, one can only do this when using no template, which is quite generous

**Comment by saadkadhi** [comment]
So you want to have the ability to add additional tasks right after you've selected the case template from the list instead of having to make 2 extra clicks (click on the *Tasks* tab then click on the *+Add Task* button)?

**Comment by commiaI** [comment]
Yes, I'm lazy :)
