### ISSUE TITLE
Make The Hive working on any URL path and not only /

### ISSUE THREAD

**Issue by vacmf** [CERT-BDF/TheHive#114]
### Request Type
Feature Request

### Problem Description
Currently it is not possible to have The Hive fully working on a URL path other that root, without changing the code.

For instance:
* https://thehivedomain.tld/
works
* https://myservicesdomain.tld/thehive/ 
doesn't work. 
Relative URLs are ok and sent to the expected path (e.g. /thehive/...), but for example front-end API requests are sent to /api/ with no option to configure it.

#### Use case
Have The Hive running on a domain together with other software. 
Sometimes it's not possible/allowed to have different (sub)domains or ports for different services, therefore being able to use a specific path within a common domain is the only option at hand.

Thanks
lorenzo

**Comment by nadouani** [comment]
This is fact occurring because the Front-End uses absolute URLs '/api/' to call the Backend-Services.
We will cook a solution for that.

**Comment by nadouani** [comment]
We updated the front end to use relative API urls, that way you can proxify them using your reverse proxy.
