### ISSUE TITLE
Include Dockerfile in Repo

### ISSUE THREAD

**Issue by JohnOmernik** [CERT-BDF/TheHive#117]
# Include Dockerfile for building docker containers in TheHive repo
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Docker
| OS version (client)       | Docker
| TheHive version / git hash   | Master
| Package Type              | Docker
| Browser type & version    | N/A

### Problem Description
Please include the Docker files so we can build internally.

### Steps to Reproduce
N/A
### Possible Solutions
Include Dockerfile in ./docker

**Comment by To-om** [comment]
Dockerfile is generated by sbt [native-packager](http://www.scala-sbt.org/sbt-native-packager/) plugin. You can generate it using the command (from sources):
```
bin/activator docker:stage
```
Then you will find all you want in `target/docker/stage` folder. The Dockerfile content is:
```
FROM elasticsearch:2.3
EXPOSE 9000
WORKDIR /opt/docker
ADD opt /opt
RUN ["chown", "-R", "daemon:daemon", "."]
RUN ["mkdir", "-p", "/data"]
RUN ["chown", "-R", "daemon:daemon", "/data"]
VOLUME ["/data"]
USER daemon
ENTRYPOINT ["bin/entrypoint"]
CMD []
```

**Comment by dafal** [comment]
It would be great to have the Dockerfile in the repository.  Before installing an image I used to check the dockerfile.  In this case I have to clone the repository and generate the file using the native-packager or to have a look at the [TheHive/build.sbt](https://github.com/TheHive-Project/TheHive/blob/4e42dba9e1a5667054583923c1c11416d76de5c5/build.sbt) file but it is not clear if you don't know how this native-packager works.

**Comment by ilyaglow** [comment]
Dockerfile alone can be used for an Automated Build option on docker hub, so you won't be bothered anymore to push images by yourself and as a bonus providing transparency for end users about what container really contains :)

**Comment by ilyaglow** [comment]
If anyone interested, I've made a dockerfile that builds image using github repository only: https://github.com/ilyaglow/dockerfiles/blob/master/thehive/Dockerfile

**Comment by hilt86** [comment]
I followed the instructions and installed sbt and then used sbt docker:stage to generate a Dockerfile. I know close to nothing about Scala and nevertheless the build had some errors and was looking for credentials for Bintray, which appears to prevent the binaries from being built.

In summary the process as described either doesn't work or you need to be familiar with Scala to build a docker container. Usually Docker images build the binaries within the container and the docker.sbt seem to be generating the files and then copying them to the container, which I would guess could lead to very different Docker images depending on local versions.

Is there any way we can improve the build process and the Dockerfile generation process that doesn't require specialized knowledge?

**Comment by james-mchugh** [comment]
What are the advantages to automatically generating the Dockerfile as opposed to having one included in the repository? To me saying just that it can be generated and closing the issue is a poor response, as it is an antipatern for most tools that utilize Docker. It would be nice to have justification for why generating the Dockerfile is better.
