### ISSUE TITLE
Question on disabling HTTP after enabling HTTPS

### ISSUE THREAD

**Issue by mars01** [CERT-BDF/TheHive#120]
### Request Type
Explanation

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu,
| OS version (client)       |  Windows 7
| TheHive version / git hash   | 2.10
| Package Type              |  From source
| Browser type & version    | Chrome

Hi, how do I disable HTTP once I have HTTPS up and running? I tried disabling ports in the systemD script and the install thehive.conf file, no luck.

**Comment by To-om** [comment]
Hi,

You can disable HTTP with the settings `http.port=disabled`. This settings can be added in `application.conf` or in command line argument (`-Dhttp.port=disabled`).

I've updated the [FAQ](https://github.com/CERT-BDF/TheHive/wiki/FAQ#can-i-enable-https-to-connect-to-thehive)
