### ISSUE TITLE
Question on Elasticsearch Tuning

### ISSUE THREAD

**Issue by JohnOmernik** [CERT-BDF/TheHive#122]
# Question on Elasticsearch Tuning

### Request Type
 Feature Request

### Work Environment

NA/General Question/Feature

### Problem Description
When the Elasticsearch index is created, what is the default setup for indexes (number of shards, replicas, etc).  Can this be a tunable thing? For example, if I am using a ES cluster that has 4 nodes, could I ensure that I can take any node down for maintenance by increasing the number of default replicas when thehive creates its indexes for the first time?  

### Possible Solutions
Configuration items allowing for sane defaults and more control over creation parameters.  (Also documentation on them.)

**Comment by To-om** [comment]
Currently, index is created using [default settings](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-create-index.html#CO119-1) (number_of_shard: 5, number_of_replicas: 1).

After index creation it is possible to [update the number of replicas](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-update-settings.html#indices-update-settings). I think that number of shards can't be modified without reindexing all data.

I'll add settings in TheHive configuration to specify index settings.

**Comment by To-om** [comment]
I've created an [issue](https://github.com/CERT-BDF/elastic4play/issues/9) for that.
