### ISSUE TITLE
Improve logs browsing

### ISSUE THREAD

**Issue by jeromeleonard** [CERT-BDF/TheHive#128]
### Request Type
Feature Request

### Work Environment
Any

### Problem Description
As an analyst working on a case, viewing the most recent log in tasks is very helpful. But as someone taking notes of the case, it would be more helpful to be able to choose to review logs the less recent first.

**Comment by nadouani** [comment]
The task logs list have been improved by adding a size page selector and a sort option

![screen shot 2017-04-04 at 12 15 47](https://cloud.githubusercontent.com/assets/21827/24652062/8c200238-1930-11e7-96fb-1072f8840e76.png)
