### ISSUE TITLE
Display short reports on the Observables tab

### ISSUE THREAD

**Issue by saadkadhi** [CERT-BDF/TheHive#131]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 2.10.0
| Package Type              | Binary

### Problem Description
The *Observables* tab is not currently very useful as it doesn't show short reports resulting from executed analyzers that would allow analysts to quickly weed through a large number of observables and/or aid their decision-making process. 

### Possible Solutions
Whenever a analyzer that supports short reports is executed such as VT or MaxMind, display the resulting short reports in the *Observables* page next to the observable.

Add the ability to filter against the short reports. For example, the analyst should be able to isolate all observables located in a particular country and apply complementary analysis etc.

**Comment by saadkadhi** [comment]
This is something we have identified for quite some time and is on our roadmap for Q2/Q3. We are going to freshen the UI with 2.12.0 and the new UI will display that info.

**Comment by bullerdude** [comment]
We are also very keen to see this feature introduced to enable quicker identification of relevant/malicious observables. Ideally all the short-report tags should be shown as part of the observable table.

**Comment by nadouani** [comment]
This feature will have a dependency on Cortex 1.5.0 release
