### ISSUE TITLE
Set assignee for case on case create via API

### ISSUE THREAD

**Issue by amateur-professional** [CERT-BDF/TheHive#133]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04 LTS
| OS version (client)       | N/A
| TheHive version / git hash   | 2.10
| Package Type              | Source
| Browser type & version    | N/A

### Request
Now that theHive has the "assignee" field for Cases as of 2.10, is there any way to set this field via API submission in a new case? I was originally setting the owner of a Triage task in each case as a substitute, but the API documentation does not mention a way to set the assignee of cases.

**Comment by To-om** [comment]
Assignee is stored in "owner" field. If it is not set at case creation, the user who submit the creation is used. If you want to assign the new case to another user you can set the field "owner":
```
curl -XPOST -u myuser:mypassword -H 'Content-Type: application/json' http://127.0.0.1:9000/api/case -d '{
  "title": "My first case",
  "owner":"otheruser",
  "description": "This case have been created by my custom script"
}'
```
