### ISSUE TITLE
Typo in quick filters

### ISSUE THREAD

**Issue by derDuffy** [CERT-BDF/TheHive#134]
### Request Type
Bug
### Problem Description
There is a typo in the quick filters. It's called "Closes Cases" where it should be "Closed cases" I guess.

### Complementary information
Also as the filter status is then called "Resolved" it would maybe be a good idea to call the quick filter "Resolved Cases" just to stick with the wording - but I know I'm really picky now :)

**Comment by nadouani** [comment]
I've fixed the typo but renaming the "Resolved" status to "Closed" requires a data migration (for existing data), so we will include it in the next migration (not yet planned)
