### ISSUE TITLE
Issue with Misp, no connection

### ISSUE THREAD

**Issue by lanbus** [CERT-BDF/TheHive#135]
Misp configured but no querry is sent. logs are saying error on host.

### Request Type
Bug/ Implementation Error

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 2.x, hash of the commit
| Package Type              | Binary
| Browser type & version    | If applicable

### Problem Description
The synchronisation with the Misp is not trying on the network.

### Steps to Reproduce
I configured the option as in the documentation: 
43 ## Enable the MISP module
 44 play.modules.enabled += connectors.misp.MispConnector
45
 46 misp {
 47   "MISPPERSO" {
 48       # URL of the MISP server
 49       url = "https:\\misp.mydomain"
 50      # authentication key
 51       key = "The long authentication key"
 52     # tags that must be automatically added to the case corresponding to the imported event
 53       tags = ["misp"]
 54     }
 55
 56   # truststore to use to validate the MISP certificate (if the default truststore is not sufficient)
 57     cert = /opt/truststore3.jks
 58
 59   # Interval between two MISP event import in hours (h) or minutes (m)
 60     interval = 1h
 61 }
~
And restarted the service. It may be a typo mistake or something but I can't see it...

### Complementary information
Feb 24 15:33:48 ticketingcert thehive[8024]: [#033[37minfo#033[0m] c.misp.MispSrv - Update of MISP events is starting ...
Feb 24 15:33:49 ticketingcert thehive[8024]: [#033[31merror#033[0m] a.d.TaskInvocation - host
Feb 24 15:33:49 ticketingcert thehive[8024]: java.lang.NullPointerException: host
Feb 24 15:33:49 ticketingcert thehive[8024]: at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
Feb 24 15:33:49 ticketingcert thehive[8024]: at org.asynchttpclient.uri.Uri.<init>(Uri.java:65)
Feb 24 15:33:49 ticketingcert thehive[8024]: at org.asynchttpclient.uri.Uri.create(Uri.java:38)
Feb 24 15:33:49 ticketingcert thehive[8024]: at org.asynchttpclient.uri.Uri.create(Uri.java:31)
Feb 24 15:33:49 ticketingcert thehive[8024]: at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:148)
Feb 24 15:33:49 ticketingcert thehive[8024]: at play.api.libs.ws.ahc.AhcWSRequest.buildRequest(AhcWS.scala:252)
Feb 24 15:33:49 ticketingcert thehive[8024]: at play.api.libs.ws.ahc.AhcWSRequest$$anon$2.execute(AhcWS.scala:166)
Feb 24 15:33:49 ticketingcert thehive[8024]: at play.api.libs.ws.ahc.AhcWSRequest.execute(AhcWS.scala:168)
Feb 24 15:33:49 ticketingcert thehive[8024]: at play.api.libs.ws.WSRequest$class.get(WS.scala:453)
Feb 24 15:33:49 ticketingcert thehive[8024]: at play.api.libs.ws.ahc.AhcWSRequest.get(AhcWS.scala:107)

**Comment by nadouani** [comment]
Hi, could you please double check your MISP URI.

> url = "https:\misp.mydomain" 

The URL seems malformed

**Comment by lanbus** [comment]
Mmm, it is  url = "https:\\misp.mydomain" in my conf.
Must have removed something when I changed the domain name by mistake.

**Comment by lanbus** [comment]
ok, no it is the site that change it. there is 2 \

**Comment by nadouani** [comment]
OK the URL is not valid, is should be 

```
 url = "https://misp.mydomain"
```

not 

```
 url = "https:\\misp.mydomain"
```

**Comment by lanbus** [comment]
Oups, Stupid mistake. Sorry! Thanks for the quick answer!
