### ISSUE TITLE
Connect to Cortex instance via proxy

### ISSUE THREAD

**Issue by bullerdude** [CERT-BDF/TheHive#147]
### Request Type
Feature Request

### Work Environment
Ubuntu, 2.x, Binary

### Request Details
Ability to link The Hive to Cortex servers via a proxy server. This supports use-cases such as running The Hive on premise and multiple Cortex instances in the cloud (e.g. azure).

**Comment by nadouani** [comment]
Hi, this is in fact the same request as #143

**Comment by bullerdude** [comment]
An additional thought regarding the proxy issue. We are looking for the ability to define a proxy server per cortex instance, as some cortex instances will not require a proxy. For example, a proxy server is required to connect to a cloud hosted cortex instance but it is not required to connect to a local on-prem hosted cortex instance.

**Comment by nadouani** [comment]
Yes, you will be able to define a proxy config for each declared cortex instance in Thehive config file
