### ISSUE TITLE
Observable Tags not displayed in 2.10.1

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/TheHive#155]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 2.10.1
| Package Type              | Bin
| Browser type & version    | Chrome

### Problem Description
Short information/tags using short.html templates are not displayed in v2.10.1. When switching back to v.2.10.0 they appear again.

### Steps to Reproduce
1. Update to 2.10.1 -> "Tags" are gone
1. Revert update -> Tags appear again

Maybe I missed something important regarding template changes or so?!

**Comment by nadouani** [comment]
Hi @3c7 

Are you talking about the "Labels" that we display in the header of observable details page? The Labels you can see after you run some analysis jobs on that observable?

**Comment by 3c7** [comment]
@nadouani Yeah, right. They're not displayed in 2.10.1. I'm update my setup through symlinking to the newest version, so I can quickly revert back. When using 2.10.0 everything is displayed correctly.

**Comment by nadouani** [comment]
Does this issue occur also for new observables analyzed with 2.10.1?

**Comment by nadouani** [comment]
@3c7 I think that for a better investigation, you can DM me on https://gitter.im/TheHive-Project/TheHive ;)

**Comment by 3c7** [comment]
Yeah, finished templates for google safebrowsing today and recognised that while testing.

**Comment by nadouani** [comment]
Ok, can you get the details of your observable, and check if it contains a `reports` attribute (it should include the summaries of all the successful analysis made on this observable)?

**Comment by nadouani** [comment]
After some investigation, the issue comes from the All-In-One binary package.

**Comment by saadkadhi** [comment]
We have fixed the problem with the all-in-one binary package and [published a new one](https://dl.bintray.com/cert-bdf/thehive/thehive-cortex-latest.zip). We apologize for any inconvenience this issue might have caused you and invite you to update your current installation. 

I am going to close this issue but feel free to reopen it should you encounter problems with the latest package.
