### ISSUE TITLE
Persistence for task viewing options

### ISSUE THREAD

**Issue by megan201296** [CERT-BDF/TheHive#157]
# Persistence for task viewing options

### Request Type
 Feature Request

### Request 
Currently, you can change the task view to show a different number of tasks per page. However, it is not persistent so even if you adjust it to more, it reverts as soon as you leave the tab/page. Since most our templates have over 10 tasks, it would be nice for it to default to a higher number if we choose. At the very least even if we can't change the default, it would be nice for it to persist for the specific case you work after you adjust it so that you don't have to change it constantly.

**Comment by nadouani** [comment]
As a quick fix for this issue, we could set the default items per page to 30. 
In the future we will add user preferences and persistence.
