### ISSUE TITLE
Job status refresh

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/TheHive#171]
### Request Type
Bug

### Work Environment
TheHive v. 2.10.1

### Problem Description
If the TheHive process gets killed while running a job, the job is persistently displayed with a gear symbol. Maybe it's possible to update events in that status when TheHive gets restarted and put them into failed state.

**Comment by 3c7** [comment]
![Visualization](https://cloud.githubusercontent.com/assets/2846609/24911979/0d9ca414-1ecd-11e7-9d9f-14e97ae4b2a4.png)

The oldest job is still spinning, because I restarted TheHive accidentally while querying.

**Comment by nadouani** [comment]
Hi @3c7, thanks for reporting this one. We've already seen it but forgot to track it :)
