### ISSUE TITLE
session timeout

### ISSUE THREAD

**Issue by juanpablobr** [CERT-BDF/TheHive#172]
Hi 

I want to know if it's possible to modify the session timeout in TheHive, want i want to achieve is create a user that could login in a  TV screen with read only privileges and show the timeline and dashbooard there.

Thanks in advance

**Comment by nadouani** [comment]
Hi @juanpablobr when you say "session timeout" you mean the amount of time after which the UI asks if you are still connected and then switches to the login form?

**Comment by nadouani** [comment]
TheHive has this type of configuration but it's global to all the users, not specific for a given user:

Just add the following configuration property. could be `Xm` or `Xh`or `Xd`

For example, for 1 day timeout, you can set

```
session.inactivity = 1d
```

The current default value is `1h`

**Comment by Nymeria1** [comment]
hello,
where can I set that configuration.property?
In my system thehive installed via docker.
Many thanks for help
