### ISSUE TITLE
Connect to Cortex protected by Basic Auth

### ISSUE THREAD

**Issue by bullerdude** [CERT-BDF/TheHive#173]
### Request Type
Feature Request

### Work Environment
Ubuntu 16.04
The Hive 2.10.1
Built from source

### Details
We have deployed Cortex behind an NGINX reverse proxy enabling SSL and basic authentication to protect the Cortex instance. This is primary due to running cloud hosted Cortex instances that cannot be left openly accessible via the internet.

To facilitate this we had added a simple basic authentication option to the code and re-compiled the binary for our environment. It would be good if this feature could be added to the master for all to benefit.

**Comment by saadkadhi** [comment]
Hi @bullerdude. We welcome PRs. Please submit one on the [Cortex](https://github.com/CERT-BDF/Cortex/) repository. Otherwise it'll have to wait for Cortex 2.

**Comment by bullerdude** [comment]
Hi @saadkadhi. We have created a PR with the updated code.
