### ISSUE TITLE
Choose case template while importing events from MISP

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/TheHive#175]
### Request Type
FR

### Work Environment
v. 2.10.1

### Feature Request
It should be possible to choose the report template to use while doing a MISP import. So the incident handler can react to different situations/events/etc.

**Comment by saadkadhi** [comment]
@3c7 Thanks for the FR which makes a lot of sense. It will be implemented in Mellifera 1, the first rev of the next major release. We intend to release Mellifera in mid-May and Mellifera 1 by the end of May.
