### ISSUE TITLE
Assign default metric values

### ISSUE THREAD

**Issue by 3c7** [CERT-BDF/TheHive#176]
### Request Type
Feature Request

### Feature Request
It would be cool if default values can be assigned to metrics - either general or per case template, I'm not sure what would be more useful.

**Comment by nadouani** [comment]
I would say that both cases could be useful :)

**Comment by woifi** [comment]
+1

**Comment by nadouani** [comment]
The administration section will allow setting default values to metrics when attached to case templates.
