### ISSUE TITLE
API Case Creation not parsing payload correctly

### ISSUE THREAD

**Issue by amateur-professional** [CERT-BDF/TheHive#178]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.x
| OS version (client)       | Ubuntu 16.x
| TheHive version / git hash   | 2.10.1
| Package Type              | From source
| Browser type & version    | N/A

### Problem Description
API Case Creation with a JSON-formatted payload using the Python Requests library does not correctly detect the presence of the 'title' and 'description' fields.

Our use case is a Python script automatically creating cases with a JSON payload. A sample payload is below:
```
{
	"tags": ["badIP"],
	"title": "(redacted)",
	"tlp": 1,
	"severity": 2,
	"tasks": [{
		"title": "Triage",
		"description": "Determine whether this case is a false positive, indeterminate, or a true positive. Do not close the case without completing this task."
	},
	{
		"title": "Determine Scope",
		"description": "Find all affected machines, users, IPs, etc. Log them in the Observables section."
	},
	{
		"title": "Notify Customer",
		"description": "(redacted)"
	}],
	"description": "3389 connections",
	"flag": true
}
```
This is copied directly from the script logs - this is the exact payload the script is attempting to deliver to theHive. Attempting to create the case via curl command, as detailed on the API documentation page, works **with this particular payload** and others also generated by the same script. However, theHive's logs indicate that two fields are missing when creating the case from the script:
```
 [INFO] from application in application-akka.actor.default-dispatcher-2085 - POST /api/case returned 400
org.elastic4play.AttributeCheckingError: [Attribute title is missing][Attribute description is missing]
```
Obviously these attributes are not missing; the curl command would have failed if they were. Any ideas?

**Comment by nadouani** [comment]
Hi @amateur-professional 

Could you please post the snippet of python code used to create the case from this type of payload?

Or could you consider using our TheHive4Py libary (https://github.com/CERT-BDF/TheHive4py).
You can find some samples of how to use it to create cases with tasks:

https://github.com/CERT-BDF/TheHive4py/blob/master/samples/test-case-create.py

**Comment by To-om** [comment]
Hi  amateur-professional,

The payload is correct and it is accepted by TheHive. The following command:
```
$ curl -XPOST -u user:password 'http://127.0.0.1:9000/api/case' -H 'Content-Type: application/json' -d '
{
  "tags": ["badIP"],
  "title": "(redacted)",
  "tlp": 1,
  "severity": 2,
  "tasks": [{
    "title": "Triage",
    "description": "Determine whether this case is a false positive, indeterminate, or a true positive. Do not close the case without completing this task."
  },
  {
    "title": "Determine Scope",
    "description": "Find all affected machines, users, IPs, etc. Log them in the Observables section."
  },
  {
    "title": "Notify Customer",
    "description": "(redacted)"
  }],
  "description": "3389 connections",
  "flag": true
  }'
```
returns expected result:
```
{"startDate":1492168711142,"createdBy":"user","tlp":1,"title":"(redacted)","flag":true,"user":"user","tags":["badIP"],"createdAt":1492168711116,"status":"Open","owner":"user","description":"3389 connections","severity":2,"caseId":1406,"id":"AVtsL5vodb_c8N_Ni1On","_type":"case"}
```

The problem is located in your script.

**Comment by amateur-professional** [comment]
We've determined the problem; Requests library was not specifying the content-type of the POST (even though it should have been). Forcing the issue has fixed the problem. Thanks!
