### ISSUE TITLE
Cannot distinguish which analysers run on which cortex instance

### ISSUE THREAD

**Issue by bullerdude** [CERT-BDF/TheHive#179]
### Request Type
Feature Request

### Problem Description
The Hive currently does not show the Cortex instance associated with each analyser. This makes it difficult to understand where the analysis will be performed (e.g. local on-prem cortex instance or cloud cortex instance).

### Possible Solutions
Would be good if there is an option to group analysers by cortex instance or prefex the name of each analysers with the cortex instance name.

**Comment by nadouani** [comment]
We could display the Cortex servers on which a given analyzer is available
