### ISSUE TITLE
Link cases

### ISSUE THREAD

**Issue by juanpablobr** [CERT-BDF/TheHive#182]
**Request Type**

Feature Request

**Possible Solutions**

In some cases you open a new incident or alert just to find out in the triage process that the same alert/event/anomaly was treated a couple of weeks ago. In this situation It could be very useful to have a field in the case to insert the number of another cases related.

**Comment by saadkadhi** [comment]
Hi @juanpablobr. TheHive links cases through their observables. Whenever you add an observable to a case that has been already included in another, a link is created and you can see this in the case's description tab as well as in its title 'bar'. Moreover, observables that have been seen somewhere else will have an 'eye' icon in the observables tab.

This feature automatically computes the number of linked cases and displays not only the number of related cased but also the most recent and the oldest with the number of shared observables with hyperlinks to go explore those cases/observables.

So I believe what you are looking for is already implemented. If that's not correct, please elaborate so we can precisely understand your needs. You may also come and chat with us on [Gitter](https://gitter.im/TheHive-Project/TheHive) if that's easier.

**Comment by juanpablobr** [comment]
Hi @saadkadhi thanks for the explanation, that is what I was looking for. We are just doing test cases currently so we probably did not have cases with the same observable yet.

**Comment by saadkadhi** [comment]
Thanks for your feedback. I am going to close this issue then. Feel free to reopen it if the current implementation doesn't fulfill your requirements.

**Comment by vlabmichl** [comment]
@saadkadhi besides linking cases automatically is there something like a MD shortcut to reference / mention one Case from another (or to mention an Alert in a Case)?

I think of something like a ```#123``` shortcut to mention "Case 123".
