### ISSUE TITLE
Reopen tasks

### ISSUE THREAD

**Issue by juanpablobr** [CERT-BDF/TheHive#183]
**Request Type**

Feature Request

**Problem Description**

Sometimes a team member could close a task without doing it correctly.

**Possible Solutions**

Would be good if there is an option to reopen a task previously closed. This option should be available only in open cases.

**Comment by nadouani** [comment]
Hello @juanpablobr Thanks for the request. It's a duplicate of #156, so we will close this one and track the changes via #156
