### ISSUE TITLE
Msg_Parser analyser show for all files

### ISSUE THREAD

**Issue by bullerdude** [CERT-BDF/TheHive#184]
### Request Type
Bug

### Problem Description
The Msg_Parser is show as a possible for analyser for all file observables despite only working for email messages.

### Possible Solutions
Perhaps create a new 'Email' observable type for uploading emails, which would allow for the Msg_Parser to be associated with only the 'Email' observables.

**Comment by saadkadhi** [comment]
That is indeed a serious limitation and one that we are going to work hard to fix as soon as feasible. Thank you for raising it @bullerdude.

**Comment by jeromeleonard** [comment]
This issue better suits in Cortex-Analyzers. Opened as #[136](https://github.com/CERT-BDF/Cortex-Analyzers/issues/136) - https://github.com/CERT-BDF/Cortex-Analyzers/issues/136.

Many solutions can be implemented. One could be to improve FileInfo and make msgparser  a subprogram for mails. Another could be to make Cortex acts regarding the the content-type/mimetype of a file.
