### ISSUE TITLE
Specifying tags on statistics page or performing a search

### ISSUE THREAD

**Issue by mcgheeshawnd** [CERT-BDF/TheHive#186]
# Ability to perform 'and' when specifying tags on the statistics page or performing a search

### Request Type
Feature Request

Having the ability to choose whether the tags section uses 'or' or 'and' would be useful.  For example, 'tag1' and 'tag2' and 'tag3'.  At the moment it appears to default to 'or'.

**Comment by nadouani** [comment]
Hello,

the tags filter of statistics page will be enhanced to allow filtering by:
- "Any of"
- "All of"
- "None of"
...list of tags

![screen shot 2017-06-08 at 17 30 25](https://user-images.githubusercontent.com/21827/26936951-6553606e-4c70-11e7-98ec-7c25374dad47.png)

This will help users to exclude cases from their statistics
