### ISSUE TITLE
Coments on cases/tasks

### ISSUE THREAD

**Issue by fehrnah** [CERT-BDF/TheHive#190]
**Feature Request**

Is there any plan to add the ability to comment on a Case/task.

Right now the only way to do so seams to edit the description.

**Comment by nadouani** [comment]
Hello, is this different from what is aimed by the task logs?

**Comment by saadkadhi** [comment]
@fehrnah I am going to close this one right now. Feel free to reopen it if you task logs, task and case descriptions, case summary, tags, do not fulfill your needs.
