### ISSUE TITLE
Give us something to work with!

### ISSUE THREAD

**Issue by MartinIngesen** [CERT-BDF/TheHive#2]
Hey!
This looks like a really cool project, and something that I would like to contribute to. The way I usually contribute to such projects is by looking at the "Issues"-page of a repo and see if there is something there which I can work towards. I like this because of two reasons (1) it gives me a clear goal for a feature, (2) It makes me more confident that I am adding something of value to the project. I am of course going to deploy it on my own and have a look around, but I know from past experience that that's a tougher path to contributing something useful.

### Request Type
Question

### Possible Solutions
What I'm hoping for is that the people who "owns" this project maybe sits down and spends a few minutes thinking of stuff that "would be cool to add but I don't have the time to implement", and share them as issues. Even trivial features such as "make footer slimmer" or whatever could help spur the interest in contributing, in my opinion!

I'm not trying to be harsh here, I just want to contribute to what looks like an awesome project! 👍

**Comment by saadkadhi** [comment]
Thank you for your interest in our project. We do have a roadmap and a plan to deliver on it. We will be publishing it shortly. In the meantime, we invite you to watch the feature requests that users would open on GitHub and if something looks like within your reach and you are interested in implementing, state so on the corresponding issue and perform a pull request. 

We are looking forward for your contributions.
