### ISSUE TITLE
Advanced user/groups roles.

### ISSUE THREAD

**Issue by MariasStory** [CERT-BDF/TheHive#202]
### Request Type
Bug / Feature Request

### Problem Description
Is there a way to get users permissions organized in groups comparable to MISP - organizations based?
Is there a user groups management concept?
Is there a case integrity concept? Limited access to the tickets that owned by one group from another and notification of the ticket author about changes to the ticket from another investigator.

### Steps to Reproduce
Create users and try to isolate/transfer tickets from one group to another.
Modify tickets of another investigator and try to follow the changes in the text fields (task logs, ...)

### Possible Solutions
Create users groups/organizations. The user management schema could be taken from MISP.

### Complementary information
TheHive
2.10.2
Elastic4Play
1.1.4
Play
2.5.14
Elastic4s
2.3.0
ElasticSearch
2.3.0

**Comment by saadkadhi** [comment]
Hi @MariasStory, this issue is similar to #162 and, to some extent, #103. Since #162 is very close to your FR, I am going to close yours and I kindly ask you to add any complementary user role related feature to #162 instead.

Our current plan is to implement it by Q4 2017 / Q1 2018 with v 3.0.0.

**Comment by MariasStory** [comment]
Hi @saadkadhi I don't understand the point of closing an issue and referencing it to another closed issue #162 .
So, what is the reference issue that can be tracked?
I guess you are working on incidence management platform and would like to see that you are able to track the issues on github.

**Comment by MariasStory** [comment]
Ok, I see you kind of do it in #103 . Although, it is not the same with what I've been asking.

**Comment by saadkadhi** [comment]
I think your following sentence is mean: 

>  I guess you are working on incidence management platform and would like to see that you are able to track the issues on github.

Offense taken.
