### ISSUE TITLE
Reordering Tasks

### ISSUE THREAD

**Issue by ecapuano** [CERT-BDF/TheHive#21]
(Request Type)
Feature Request

Would be nice to be able to reorder tasks that are part of a Case Template in order to provide an "order of operations" for tasks...

Specifically in the event that some tasks may be higher priority, or may be dependent on other tasks. The ability to reorder them would be ideal. 

Currently, one would have to delete and re-add tasks in order to add a new one above pre-existing ones.

**Comment by saadkadhi** [comment]
This is worth considering. 

As a workaround, you can change the task orders by using a prefix (1., 2., 3. ...). This will automatically change their order as they are sorted.

Note also that flagged tasks are always displayed first.

**Comment by derDuffy** [comment]
I would second that request, I was facing a similar problem while trying to "implement" our process in TheHive

**Comment by megan201296** [comment]
I third this request. Maybe a drag a reorder type thing.

**Comment by megan201296** [comment]
Do you think this is something that will be implemented anytime soon? Could be very valuable. As we are learning how TheHive works and implementing our procedures in we are constantly adding to the templates, making us wish we could reorder (in an easier/less messy way than appending numbers).

**Comment by saadkadhi** [comment]
We hear you and we are definitely going to do it. However we have more important features to implement in the upcoming weeks.

We plan to make it possible to reorder tasks by Q2 2017.

**Comment by nadouani** [comment]
We just added a drag&drop ordering feature for case template tasks.
