### ISSUE TITLE
report status not updated after finish

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#212]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 2.11.1-1
| Package Type              | DPKG

### Problem Description
When running an Analysis after Analysis with Cortext finished the Status is still "no Reports available"
After refreshing the page, the Report is there.

### Steps to Reproduce
Run an Analysis wait for end and if the Status changes on the observable.

**Comment by MariasStory** [comment]
Confirm the behavior.

**Comment by nadouani** [comment]
Well, the "Analysis" column we included within 2.11.1 was a quick addition to allow users to quickly know if an observable has been analyzed or not.
This column is in fact not refreshed based on job status in real time, and in a next feature we will support that.

Anyways, I confirm it too, and this issue will help tracking that improvement.

Thanks

**Comment by crackytsi** [comment]
Please also note, that if I create and Observable the list is also not refreshed. So I need to change the tabs before the newly created item appears...
