### ISSUE TITLE
Timeline does not work.

### ISSUE THREAD

**Issue by MariasStory** [CERT-BDF/TheHive#214]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 2.11.0
| Package Type              | Binary

### Problem Description
In the "statistics" tab, the "Cases over time", "Cases handling over time" and "Observables over time" show only one time point.

### Steps to Reproduce
1. Create events over time.
2. Check the statistics.

### Possible Solutions
Did not debug it jet.

### Complementary information
![image](https://cloud.githubusercontent.com/assets/6576335/26193571/01db3c70-3bb6-11e7-9244-e181f90fec83.png)

**Comment by nadouani** [comment]
Hello, 

please share the whole graph panel's screenshot, including the panel's header, to see what are the options of your graph

Thanks

**Comment by MariasStory** [comment]
Sure:
![image](https://cloud.githubusercontent.com/assets/6576335/26198584/d2f121ac-3bc6-11e7-8e74-6c05e243e358.png)

I guess that this one is a similar issu: #215

**Comment by nadouani** [comment]
So, based on this screenshot, you are displaying cases over time and grouping them by month. I also suppose that in the header of the statistics page, you selected a 1 month period.

Correct me if I'm wrong, you are 
- displaying the cases of a month
- grouping them by month 

=> which results on just one chart plot, as shown by the screenshot.

Is this correct?

**Comment by MariasStory** [comment]
Hi @nadouani,

Thanks for the clarification.

I did not realize that the events are grouped.

Maybe it wold be better to put an "Interval:" for the report period and a "group by:" field for grouping?

**Comment by nadouani** [comment]
Statistics section will be reviewed when adding support to custom dashboards creation, so we will treat that at that moment.

For now, I'll close this issue as invalid.

Nabil

**Comment by MariasStory** [comment]
Just to add, I was a bit confused. I see that there is a report period on top.
Thanks for support.

**Comment by nadouani** [comment]
Yes the report period on top is global to all the graphs
