### ISSUE TITLE
Statistics: Observables and IOC over time

### ISSUE THREAD

**Issue by garanews** [CERT-BDF/TheHive#215]
### Request Type
 Feature Request

### Work Environment

TheHive v2.11

### Problem Description
In the statistics page there is no shown the IOC over time

### Possible Solutions

![ioc](https://cloud.githubusercontent.com/assets/16938405/26194795/dd825bfc-3bb9-11e7-8cac-60d4204ecaac.png)

**Comment by nadouani** [comment]
This request will be covered by the dynamic dashboards feature
