### ISSUE TITLE
Generation of incident report

### ISSUE THREAD

**Issue by SHSauler** [CERT-BDF/TheHive#216]
### Request Type
Feature Request

### Problem Description
Adding a button on the GUI to create a report of an incident, e.g. PDF or printable overview.

For sharing, archival and compliance purposes the export of incidents in a printable format might be a requirement for many companies. Currently we plan to do this via TheHive4py, but a GUI button would be much appreciated.

Thanks!

### Work Environment
TheHive2.11.0
Elastic4Play1.1.5
Play2.5.14
Elastic4s2.3.0
ElasticSearch2.3.0

**Comment by saadkadhi** [comment]
Hi @SHSauler, 

This feature is on our roadmap. It is extremely useful. We have it planned for Q4. This issue will help track our progress.

**Comment by nadouani** [comment]
Yes it's the same need as #125

**Comment by SHSauler** [comment]
Closing request as #125 is open with matching requirements. Thanks!
