### ISSUE TITLE
Search do not work with non-latin characters

### ISSUE THREAD

**Issue by ilyaglow** [CERT-BDF/TheHive#223]
Hey there,

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version   | 2.11.1
| Package Type              | Docker
| Browser | Chromium latest, Firefox latest

### Problem Description
If you try to search in the Hive with non-latin characters it won't work

### Steps to Reproduce
1. Create a new case with the title: `Кейс на русском языке`
2. Try to find the case: `кейс`

### Possible Solutions
It is not actually a solution but reproducing the issue with Chrome Developer Tools opened I noticed that browser don't even send XHR to the backend, so the `querystring` is getting stucked somewhere on the angular side.

**Comment by nadouani** [comment]
Hi @ilyaglow as a workaround, if you are searching for cases, you can use the search filter within cases list.

I confirm that the search box of the topbar doesn't correctly handle you search example.

Investigating...

**Comment by ilyaglow** [comment]
Hi @nadouani, workaround works great, thanks!

**Comment by nadouani** [comment]
The same thing should work through the filter form of the observables' list.

**Comment by nadouani** [comment]
Well the issue is coming from a base64 encoding library that doesn't handle non ASCII strings :)

Replacing this library by https://github.com/dankogai/js-base64 solves the issue.

**Comment by nadouani** [comment]
Latin characters can now be used and searched for, even in tags

![screen shot 2017-06-06 at 15 06 59](https://cloud.githubusercontent.com/assets/21827/26830659/da7ee870-4ac9-11e7-95fd-f8f1b5b20d63.png)

**Comment by ilyaglow** [comment]
Thank you!
