### ISSUE TITLE
Templates can not be cloned

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#226]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| TheHive version / git hash   | 2.11.1
| Package Type              | Debian package

### Problem Description
Templates can not be cloned.
If you want to copy multiple templates you need to do this manually.
It would be helpfull to have an button "save as" or a clone functionality

**Comment by juanpablobr** [comment]
I think this is very useful, teams have a defined process to manage incidents, and having the option to clone from a base template and personalize for a type of incident would be great.

**Comment by nadouani** [comment]
This is a an operation that can be covered by and export/import process implemented by #369
