### ISSUE TITLE
Task number not increased after creation within a case

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#227]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| TheHive version / git hash   | 2.11.1
| Package Type              | Debian package

### Problem Description
The Task number inside a case is not correctly increased if I create a new Task.
Same also with observables.

Steps to reproduce:
Create new Case, there are 0 Tasks. Add a Task. Number of Tasks is still 0.

**Comment by nadouani** [comment]
Do you see the changes on the live timeline on the right side?
What's the browser you use.

**Comment by crackytsi** [comment]
Yes the timeline is correctly updated.
I use Chrome Version 58.

**Comment by nadouani** [comment]
do you have many browser tabs of TheHive?

**Comment by crackytsi** [comment]
I have arround 10 Tabs open. Only on of TheHive, but also one of Cortex.

**Comment by nadouani** [comment]
Hi @crackytsi are you still encounter this issue using TheHive 2.11.2?

**Comment by crackytsi** [comment]
Hi,
Problem has disappeared.
This issue can be closed.

**Comment by nadouani** [comment]
Perfect, I was expecting that :)
