### ISSUE TITLE
Open External Links in New Tab

### ISSUE THREAD

**Issue by megan201296** [CERT-BDF/TheHive#228]
# Open External Links in New Tab

### Request Type
Feature Request

### Description
Right now if you have a link in a case and click on it, it opens it in the same tab; this essentially takes you away from TheHive. It would be nice if when you click on links to external websites it opens it in a new tab so that you can quickly look at the link and go back to TheHive seamlessly.

**Comment by nadouani** [comment]
@megan201296 I guess you are talking about links from description or summary (markdown) fields. In fact the default markdown link renderer, create `a` tags without a `_blank`target. We can customize that default behavior
