### ISSUE TITLE
Show case status and category (FP, TP, IND) in related cases 

### ISSUE THREAD

**Issue by juanpablobr** [CERT-BDF/TheHive#229]
## Request Type
Feature Request

### Problem Description
Related cases section helps analysts to find more information about an observable seen in previous cases in order to help with orientation and analysis of current case.

### Solution
In order to make the related cases section more useful to analysts, the related case summary should show the following information:

- If the related case is open (being attended right now) or closed.
- If closed, what was the final result of the related case: True Positive, False Positive, Undetermined?

**Comment by nadouani** [comment]
Hello,

currently, there a 3 places where a user could get some hints regarding related case:

1. The case details page's header

![screen shot 2017-05-31 at 16 18 21](https://cloud.githubusercontent.com/assets/21827/26636373/deca534e-461c-11e7-81e0-bc5338da36e1.png)

2. The case `summary` tab

![screen shot 2017-05-31 at 16 18 50](https://cloud.githubusercontent.com/assets/21827/26636374/def39402-461c-11e7-8e3d-7f6f9a284161.png)

3. The case `links` tab (accessible by clicking to the `See all (X related cases)`

![screen shot 2017-05-31 at 16 09 50](https://cloud.githubusercontent.com/assets/21827/26636380/e3526e88-461c-11e7-8614-8aff283a0a16.png)


The best location where we can add more details about the related cases in the `links` tab

**Comment by juanpablobr** [comment]
@nadouani agree, that is the best place to show that info

**Comment by nadouani** [comment]
We introduced the following changes:

1. From the case page's header, the `X Related case` red text, is not clickable and opens the **links** tab

1. The **links** tab shows more details about the listed case: status, close status if closed, tlp, severity etc...


![screen shot 2017-06-01 at 16 33 05](https://cloud.githubusercontent.com/assets/21827/26684805/73c6a95e-46e8-11e7-8a47-760224668dec.png)

**Comment by nadouani** [comment]
We will include a filter section on top of the list of related cases

![screen shot 2017-06-06 at 14 23 28](https://cloud.githubusercontent.com/assets/21827/26828933/c79831fe-4ac3-11e7-863f-2b556e84e905.png)
