### ISSUE TITLE
MaxMind Analyzer 'Short Report' has hard-coded language

### ISSUE THREAD

**Issue by ecapuano** [CERT-BDF/TheHive#23]
### Request Type
Bug? (but not really?)

### Work Environment

Any

### Problem Description
When running MaxMind analyzer, the short report returns the result in French, because the report code has `fr` hard coded. 
https://github.com/CERT-BDF/TheHive/blob/master/analyzers/MaxMind/report/success_short.html#L1

### Steps to Reproduce
1. Run MaxMind analyzer, observe short report in French.

### Possible Solutions
Perhaps require initial configuration of user locale in `/etc/thehive/application.conf` and import that locale code wherever needed, such as on MaxMind short report at `TheHive/analyzers/MaxMind/report/success_short.html`

### Complementary information
N/A

**Comment by nadouani** [comment]
Thanks @ecapuano the template is in fact displaying the country and city in French. We will update that and display the result based on the browser's locale. Note that Maxmind doesn't support all the languages, so we will default to english if the user's language is not supported.

**Comment by nadouani** [comment]
After a discussion, and since TheHive supports only english language and is not yet ready for i18n, we will display the maxmind location in english.
