### ISSUE TITLE
Allow AND and OR operators in filters

### ISSUE THREAD

**Issue by juanpablobr** [CERT-BDF/TheHive#230]
### Request Type
Feature Request

### Problem Description
Some use cases need to filter statistics using the existence of some TAGs at the same time in each case or observable. 

### Possible Solutions
Add a feature to choose the operator to use when searching OR/AND.

**Comment by nadouani** [comment]
Hello @juanpablobr 

this seems to be duplicate of https://github.com/CERT-BDF/TheHive/issues/186

Could you please correct me if I'm wrong? otherwise lets track that feature using #186 

Thanks

**Comment by juanpablobr** [comment]
@nadouani yes it's the same feature, will close this then
