### ISSUE TITLE
Reset Local Administrative Credentials

### ISSUE THREAD

**Issue by peasead** [CERT-BDF/TheHive#233]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | 7
| TheHive version / git hash   | 2.11.2, 06a8e15
| Package Type              | From Source
| Browser type & version    | Chrome

### Problem Description
Local authentication credentials are unknown, is there a way to reset them if I have complete access to TheHive back-end, but are unable to log into the web UI?

### Possible Solutions
Possibly a command-line utility or at the Elastic tier.

**Comment by To-om** [comment]
Hi,

You can use this script:
```
#!/bin/bash
es=http://127.0.0.1:9200
index=the_hive_9

read -p "Login: " user
read -p "New password for user $user: " password

seed=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
hash=$(echo -n $seed$password | sha256sum | awk '{ print $1 }')
curl -XPOST "$es/$index/user/$user/_update" -d '{
    "doc" : {
        "password" : "'$seed,$hash'"
    }
}'
```

**Comment by fareedfauzi** [comment]
Hey, I got a problem on version `3.4.0-1`

I create the admin credential after update the database. 

When I want to log in for the first time. The authentication failed. How can I reset the password?

**Comment by fareedfauzi** [comment]
Okay I found the solution by deleting the database.

First I find the index number of my thehive using this script

```
#!/bin/bash
for i in {1..20}
do
        curl http://127.0.0.1:9200/the_hive_$i
        echo ""
        echo ""
done
```
For my case, I found that my index is ``15`` because other number are return errors.

Then issue this command to delete database:

```
 sudo curl -XDELETE http://localhost:9200/the_hive_15
```

**Comment by nickbabkin** [comment]
Here's a script that supports newer versions of Cortex (elasticsearch 7.x):

```
#!/bin/bash
es=http://127.0.0.1:9200
index=cortex_6

read -p "Login: " user
read -p "New password for user $user: " password

seed=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
hash=$(echo -n $seed$password | sha256sum | awk '{ print $1 }')
curl -H 'Content-Type: application/json' -XPOST "$es/$index/_update/$user" -d '{ 
        "doc": {
        "password" : "'$seed,$hash'",
        "Status": "Ok"
}
}'
```

**Comment by sleven7kal** [comment]
> Here's a modified script that supports newer versions of TheHive/Cortex (elasticsearch 7.x):
> 
> ```
> #!/bin/bash
> es=http://127.0.0.1:9200
> index=cortex_6
> 
> read -p "Login: " user
> read -p "New password for user $user: " password
> 
> seed=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
> hash=$(echo -n $seed$password | sha256sum | awk '{ print $1 }')
> curl -H 'Content-Type: application/json' -XPOST "$es/$index/_update/$user" -d '{ 
>         "doc": {
>         "password" : "'$seed,$hash'",
>         "Status": "Ok"
> }
> }'
> ```
> 
> If you also forgot the username, you can retrieve all users from DB via the following request: `curl -X GET "localhost:9200/cortex_6/_search?size=5000&pretty=true&q=relations:user" -H 'Content-Type: application/json'`

I know this is an older thread but I was hoping to contact you @nickbabkin. I attempted this script however have encountered curl: (6) Could not resolve host: :<HostIP>; Unknown error. 

curl -X GET "localhost:9200/cortex_6/_search?size=5000&pretty=true&q=relations:user" -H 'Content-Type: application/json'
this worked perfectly to help me find the user and the associated index.

Any tips?

Thank you,
Shawn

**Comment by nickbabkin** [comment]
@sleven7kal just replace $es variable in the curl request with 127.0.0.1:9200 and it should work for you.
