### ISSUE TITLE
files in alerts are limited to 32kB

### ISSUE THREAD

**Issue by ant1** [CERT-BDF/TheHive#237]
I have this error with bigger files:

"type":"CreateError","message":"Document contains at least one immense term in field=\\"artifacts.data\\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[....]...\', original message: bytes can be at most 32766 in length; got 223977"

**Comment by nadouani** [comment]
Alert file observables are not longer stored as base64 encoded string but are added to the datastore as binary content.
