### ISSUE TITLE
More options to sort cases

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#243]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| TheHive version / git hash   | 2.11.3
| Package Type              | Debian package

### Problem Description
Currently Cases can only sorted by newest/oldest.
We would like the ability to sort cases also by assignee and severity.

**Comment by nadouani** [comment]
`We would like the ability to filter cases also by assignee and severity.` you mean filter or sort? :)

**Comment by crackytsi** [comment]
Sorry, I speak about sorting of course. Filtering already works nicely ;)

**Comment by nadouani** [comment]
I will add more sort options but will keep the flagged items first.
