### ISSUE TITLE
Create alert with Observables in Pyhton

### ISSUE THREAD

**Issue by ganondorf5** [CERT-BDF/TheHive#247]
### Request Type
Bug/Error

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 2.x
| Package Type              | Binary

### Problem Description
When I try to create an alert in Bash it works fine, even if I add some Observables.
When I try to create an alert in Python without Observables it works fine too.
But when I try to create an alert in Python with some Observables (according to the documentation of the alerts API) it replies :

> "{"tableName":"alert","type":"AttributeCheckingError","errors":[[{"name":"alert.artifacts","format":"nested","value":{"type":"StringInputValue","value":["dataType"]}},{"name":"alert.artifacts","format":"nested","value":{"type":"StringInputValue","value":["message"]}},{"name":"alert.artifacts","format":"nested","value":{"type":"StringInputValue","value":["data"]}}]]}"

### Steps to Reproduce
Here is my code :
```
import requests
import datetime

data = {"title": "Other alert",
  "description": "alert description",
  "type": "external",
  "source": "instance1",
  "sourceRef": datetime.datetime.now(),
  "severity": 3,
  "tlp": 3,
  "artifacts": [
    { "dataType": "ip", "data": "127.0.0.1", "message": "localhost" }
  ],
  "caseTemplate": "external-alert"
}

res = requests.post("http://127.0.0.1:9000/api/alert", data = data, auth=('user', 'passwd'))

print(res.text)
```

It's very strange and I don't know why I have this issue.
Would you know what could be the difference between sending the request with Observables in Bash and in Python ?

**Comment by nadouani** [comment]
Hello @ganondorf5 is there any reason you didn't use TheHive4py library to play with TheHive's API in python? https://github.com/CERT-BDF/TheHive4py

**Comment by ganondorf5** [comment]
Hello @nadouani I have also tried TheHive4py but I wanted to come back to something lower level to eliminate the potentials sources of bugs.
When I will be able to create an Alert with Observables using the "requests" library, it's planned that I use TheHive4py

**Comment by nadouani** [comment]
Ok, strange way of doing things but well, do it as you want :)

The issue is probably that you don't tell `requests` about the content type of your request body, which should be `application/json`

If it doesn't work, please take a look to https://github.com/CERT-BDF/TheHive4py/blob/master/thehive4py/api.py

**Comment by ganondorf5** [comment]
Thanks for your help, I've added the header `{'content-type': 'application/json'}` and converted the data in json string and it works fine now !
But I wondering why it worked before this trick without Observable and not with Observable ...

In any case, thank you !
