### ISSUE TITLE
Renaming of users does not work

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#249]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 2.12.3
| Package Type              | Binary

### Problem Description
If I try to change the username of a user (which is possible via UI), it fails with the message ({target-username} does not exist.
Possibly lock down the full rename process or make it possible (more prefered) ;)

**Comment by nadouani** [comment]
What type of authentication did you enable on TheHive instance? Local/LDAP/AD?

**Comment by crackytsi** [comment]
Sorry I forgot to add. I enabled ldap + local auth and I authenticated with an admin from LDAP.

**Comment by nadouani** [comment]
OK, Assigning to @To-om who knows more about the Authentication stuff in TheHive :)

**Comment by To-om** [comment]
User login is not modifiable as it is used as user identifier. It must not be editable in the UI. The user name hasn't this restriction.
