### ISSUE TITLE
Add multiple attachments in a single task log doesn't work

### ISSUE THREAD

**Issue by ilyaglow** [CERT-BDF/TheHive#257]
Hello there! This issue is definitely not a major one, but eventually can hit someone.

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7
| OS version (client)       | Windows 10, CentOS 7
| TheHive version / git hash   | latest
| Package Type              | Docker
| Browser type & version    | Chromium 58.0.3029.110

### Problem Description
UI allows us to attach multiple files to a single task log, but if we do it doesn't add any of the attachments, text only. One attachment per task log works well.

### Steps to Reproduce
1. Create case
2. Add task
3. Add task log with text and at least two attachments. Hive will add the text only.

**Comment by nadouani** [comment]
TheHive doesn't allow uploading multiple files by task log for now.

How was you able to add more than one file?

**Comment by ilyaglow** [comment]
Well, I can drag and drop files one by one, however only first file can be seen like it is attached.

![screenshot from 2017-07-12 20-09-47](https://user-images.githubusercontent.com/1165242/28130083-6c128f36-673e-11e7-99a5-7a0210f93f2a.png)

But if you click on "Add log", neither of files will be attached.

**Comment by nadouani** [comment]
OK, I see, if neither of the files is attached, then it must be fixed :)
