### ISSUE TITLE
Ability to see whole case history

### ISSUE THREAD

**Issue by juanpablobr** [CERT-BDF/TheHive#258]
### Request Type
Feature Request

### Problem Description
Currently you can only check a fixed number of last actions on a case. This undermines audit capabilities on the platform.

### Possible Solutions
The sidebar for a case should load on scroll groups of ten actions in descending order until the user could find the specific action that is looking for.

**Comment by nadouani** [comment]
This is in fact a good feature, but we will add an audit section instead of using the timeline to search for logs.

**Comment by saadkadhi** [comment]
Duplicate with #84 which will also feature audit trail viewing.
