### ISSUE TITLE
Newly created case template not visible in NEW case until logout/login

### ISSUE THREAD

**Issue by jkeithrainey** [CERT-BDF/TheHive#26]
A newly created case template is not available in the NEW case menu item until user has logged off/logged in again.

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 14.04.5 LTS
| OS version (client)       |  10
| TheHive version / git hash   | 2.9
| Package Type              |  From source
| Browser type & version    | Chrome 54.0.2840.71m, IE 11

### Problem Description
Newly created case template does not appear in New Case template selection until user has logged off and logged on again.

### Steps to Reproduce
1. Create new case template via the ADMIN->Case Templates menu option, fill all required fields and save template.
2. Check the +NEW menu button. The new template should appear in the list, but does not.
3. Log out user
4. Log in user
5. Check the +NEW menu button. The new template now appears in the list

**Comment by nadouani** [comment]
Hello, you don't need to logout to get the template listed, hitting refresh does the job.

Adding a template is an administrative action and is not broadcasted to all the user sessions like all the events that you can see in the timeline.
