### ISSUE TITLE
Allow Comments (Task Log) at Case Level

### ISSUE THREAD

**Issue by camobanana** [CERT-BDF/TheHive#264]
### Request Type
Feature Request

Hello,

We currently allow analysts to provide running cases level updates by having a task auto-created via the template for new cases - "Running Case Updates". This is used to provide high level semi-verbose summary updates on case progress and is useful for our workflow to see at a glance the summary of daily activity.

It would be great if we could just have case level commenting "baked in" to the case page. 

This would avoid whichever analyst posted the first comment from having that "Running Case Updates" task assigned to them until the case is closed, and allow slight more intuitive commenting.

**Comment by amateur-professional** [comment]
Why not just use the Description field?

**Comment by saadkadhi** [comment]
Hi @camobanana please use the description field as suggested by @amateur-professional. We are trying hard to keep the UI clean & lean and do not supercharge it with features. Your request will be addressed to some extent in a future UI redesign that will let you explore the 'audit trail' and hence see who has done what and when.
