### ISSUE TITLE
Make markdown/markdown editor optional

### ISSUE THREAD

**Issue by Rolinh** [CERT-BDF/TheHive#266]
### Request Type

Feature Request

### Problem Description

Rich text formatting vs plain text formatting pros/cons is an old debate and some prefer one over the other.
Nonetheless, I believe that it would be a nice addition to add an option to TheHive so that good ol' plaintext can be used in lieu of rich text formatting with Markdown.

Sometimes, using markdown even creates additional work.
Consider a script which ingests a notification from a system which has it's own formatting and creates an alert in TheHive. In this case, the script has to enclose the alert content with the code markdown markup. to prevent it from being interpreted as markdown and be badly rendered.
Another example would be a script creating alerts which potentially contain malicious URLs in their description. If the script creating the alert does not parse the alert content to defang malicious URLs, then they become clickable automatically once in TheHive interface. This obviously raises some security concerns.

**Comment by saadkadhi** [comment]
Hi @Rolinh,

We have elected to use Markdown/rich text formatting and we are not considering adding a plaintext option though you can submit a PR which we'll review and consider for addition if you make it simple for users to choose between rich and plain text fmt.

As for scripts, it's up to their developers to add formatting or ensure their output get displayed correctly by TheHive.

Malicious URLs must not be added to tasklogs unless they are disarmed and we are not going to add extra checks to prevent users or scripts from shooting themselves in the foot more than we have done at this point in other areas (such as password protected ZIP archives for files added as observables or exporting observables in defanged mode). We believe that people who care about their job and code will test it prior to production and add any necessary safeguards before raising alerts or adding tasklogs.

We do not want to babysit users more than necessary and if they work in the DFIR field they should mind their OPSEC.

Regards,
