### ISSUE TITLE
Closing a case with an open task does not dismiss task in "My tasks"

### ISSUE THREAD

**Issue by BrevilleBro** [CERT-BDF/TheHive#269]
# Closing a case with an open task does not dismiss task in "My tasks"

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| TheHive version / git hash   | 2.12
| Package Type              | From source

### Problem Description
Closing an open case with an open task should close the task. However, if the task has been assigned, the task is not dismissed from My Tasks. See below where there is only one open task, however, there are 2 for the My Tasks bade.

### Steps to Reproduce
1. Open a case
1. Assign a task to yourself
1. Close the case (which should close the task)
1. Observe the number of "My Tasks" in the header. Despite case and task being closed, the My Tasks number in the header has not changed.

### Complementary information
![image](https://user-images.githubusercontent.com/20162065/28597893-bb16bbf2-71e3-11e7-8fb4-0aee9eb07ae4.png)

**Comment by saadkadhi** [comment]
Thanks @BrevilleBro we are going to confirm this behavior and if so correct it in 2.12.1.

**Comment by To-om** [comment]
Tasks are closed but "My tasks" indicator is not updated.
@nadouani This value must be reloaded when a case is closed.

**Comment by nadouani** [comment]
This issue is a bit tricky. In fact, the "My Task" badge listens to any action made on tasks, and returned by the action stream. But when closing a case with an open task, the action stream will notify for a case update (with a sub notification of case update). 

We need to refactor the action stream service to allow listening to "sub-events"
