### ISSUE TITLE
POST Cortex Analyzer Analysis - No Reports Available

### ISSUE THREAD

**Issue by taykiin06** [CERT-BDF/TheHive#273]
# Cortex Observable Not Showing in Hive (POST Cortex Analyzer Analysis)

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Windows 7
| TheHive version / git hash   | 2.12.0
| Package Type              | Source
| Browser type & version    | Chrome v60.0.3112.78

### Problem Description
After running observables (IP, URL, etc) in Cortex Analyzers (PassiveTotal, VirusTotal...), the Hive does not show any available report from the analysis. In the observables tab in Hive, no changes and still shows "No reports available"

### Steps to Reproduce
1. Take observable from Alert/Case
1. Query the observable in Cortex
1. After successful query, refreshing the page, no changes under the observable occur

### Possible Solutions
N/A

### Complementary information
![2017-07-27_7-59-49](https://user-images.githubusercontent.com/30237370/28671294-c98c21e0-72a1-11e7-8127-5fd2da0debab.png)

**Comment by nadouani** [comment]
Hello, you said `Query the observable in Cortex`. do you mean you analyzed the observables from Cortex's UI?

**Comment by taykiin06** [comment]
Correct, analyzed the observable in Cortex.
-------- Original message --------From: Nabil Adouani <notifications@github.com> Date: 7/27/17  08:06  (GMT-06:00) To: CERT-BDF/TheHive <TheHive@noreply.github.com> Cc: taykiin06 <brad@schnur.io>, Author <author@noreply.github.com> Subject: Re: [CERT-BDF/TheHive] POST Cortex Analyzer Analysis - No Reports Available (#273) 
Hello, you said Query the observable in Cortex. do you mean you analyzed the observables from Cortex's UI?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CERT-BDF/TheHive","title":"CERT-BDF/TheHive","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CERT-BDF/TheHive"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nadouani in #273: Hello, you said `Query the observable in Cortex`. do you mean you analyzed the observables from Cortex's UI?"}],"action":{"name":"View Issue","url":"https://github.com/CERT-BDF/TheHive/issues/273#issuecomment-318356078"}}}

**Comment by nadouani** [comment]
Well, this is not the expected workflow then. If you run the analyzer from Cortex UI, then it will not be available on TheHive.

You have to launch the analyzers from TheHive to see the results on it. You can do it either from the observables list, or from the observable details page.
