### ISSUE TITLE
Alerts in Statistics

### ISSUE THREAD

**Issue by mpotgieter** [CERT-BDF/TheHive#274]
### Request Type
Feature Request

On the statistics page, it would be useful to have some metrics on alerts. Particularly an understanding of alerts versus cases will allow for useful metrics such as how many alerts are being converted into cases.

**Comment by saadkadhi** [comment]
Hi @mpotgieter. We will try to include your feature request in Cerana (3.0.0), due in October 2017. But it might be delayed until 3.1.0 (due in Dec 2017).

**Comment by To-om** [comment]
This is covered by the issue #312
