### ISSUE TITLE
Add Support for Play 2.6.x and Elasticsearch 5.x

### ISSUE THREAD

**Issue by saadkadhi** [CERT-BDF/TheHive#275]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | macOS
| TheHive version / git hash   | 2.12.0
| Package Type              | DEB
| Browser type & version    | N/A

### Problem Description
The current version of the Play framework used by TheHive (Play 2.5) does not support Elasticsearch 5 which means that we are stuck with ES 2.x.

### Steps to Reproduce
N/A

### Possible Solutions
Upgrade Play to 2.6.1 or better and ensure TheHive uses ES 5.

**Comment by peasead** [comment]
Is there a way to manually do this before 2.13?

**Comment by peasead** [comment]
The only issue I'm seeing between ES 2.4 and 5.5 (at it relates to TheHive) is an update to `/etc/elasticsearch/elasticsearch.yml` and an issue with the `the_hive_10` cluster.

If the update to `Play 2.6` happens, then this should be a moot point. That said, if you can update your `elasticsearch.yml` file and `the_hive_10` cluster, you should be able to update to `5.5` without `Play 2.6`

#### elasticsearch.yml
TheHive 2.12 Configuration
```
network.host: 127.0.0.1
script.inline: on
cluster.name: hive
threadpool.index.queue_size: 100000
threadpool.search.queue_size: 100000
threadpool.bulk.queue_size: 1000
```
TheHive 2.13 Recommendation
```
network.host: 127.0.0.1
script.inline: true
cluster.name: hive
thread_pool.index.queue_size: 100000
thread_pool.bulk.queue_size: 100000
thread_pool.bulk.queue_size: 1000
```
#### the_hive_10 Cluster
According to the [Elasticsearch Migration Plugin](https://github.com/elastic/elasticsearch-migration/tree/2.x), the Cluster Checkup failed here:
```
the_hive_10
Mappings
Parent field no longer accessible in queries
[case_artifact]:_parent
[case_task]:_parent
[case_task_log]:_parent
[case_artifact_job]:_parent
```

**Comment by peasead** [comment]
Thanks @To-om 

Should I clone the 47bfae940b53ba12d337517894f9bef090e6335d commit and follow the normal instructions to build from source?

When I get to `bin/activator clean stage` everything appears to work properly, but it doesn't seem to create the `TheHive/target/universal/` folder structure. `target/` is empty.

Here is the output from `clean stage` [thehive.txt](https://github.com/CERT-BDF/TheHive/files/1257509/thehive.txt).

**Comment by saadkadhi** [comment]
@peasead TheHive 2.13.0 will include support for ES 5. Please wait until we release it and try it out.
