### ISSUE TITLE
Statistics - Saved Filters

### ISSUE THREAD

**Issue by mthlvt** [CERT-BDF/TheHive#279]
First, thanks for the great projects around TheHive, I like the way things are designed, built and maintained!

### Request Type
 Feature Request

### Christmas List
* Ability to save a filter to build custom statistics views easily
* Ability to rename/edit/delete a filter

### Possible Solutions
* Having a drop down menu under the "Statistics" button to select a Statistic report based on saved filters (in a similar fashion as the case template drop down)
* Creating a saved filter could be done after applying a filter (button next to the search button)

Cheers,

**Comment by saadkadhi** [comment]
Hi @mthlvt, thank you for your kind comments. We are glad you think so highly of the solutions we provide.

Your feature request will probably be included in Cerana (3.0.0), due in October 2017. This major version will include dynamic dashboards.

**Comment by To-om** [comment]
This is covered by the issue #312

**Comment by mthlvt** [comment]
Kudos for the 3.0 release, the dashboard feature works great !
