### ISSUE TITLE
License Change from AGPL-3.0

### ISSUE THREAD

**Issue by a5m0** [CERT-BDF/TheHive#283]
### Request Type
Feature Request

### Problem Description
Would you consider changing TheHive (and components) license from AGPL-3.0? This license prevents use by many organizations that would like to use and contribute to this project.

### Possible Solutions
Apache 2.0
MIT License

**Comment by saadkadhi** [comment]
Hi @a5m0. Why would the AGPL license prevent organisations from using or contributing while keeping the product free and thwart commercial, for-profit versions? If so, that means that those same organisations cannot use or contribute to MISP.

Also, you cite many organisations. Please let them contact us at support@thehive-project.org or voice their concern here.

**Comment by a5m0** [comment]
I will send an email citing my organization that bans contributing to this license, thanks.

**Comment by adulau** [comment]
The AGPL section 11 allows to protect an open source project from litigious patent claims especially from contributors coming from organizations holding patents. Apache license 2.0 is partially covering the issue but the AGPL is stronger and clearer on this topic.

Maybe it's time for large organisations to reconsider their views regarding free and open source licensing. I remember in the early 2000 where large corporation didn't event want to contribute to MIT, Apache or GPL licensed software.

**Comment by iglocska** [comment]
Also, most of the time the companies that ban AGPL are the ones most notorious for keeping improvements internal.

**Comment by saadkadhi** [comment]
Thank you @adulau and @iglocska for you invaluable input and sound insight. We will keep the AGPL license.
