### ISSUE TITLE
GET /docs : Resource not found by Assets controller

### ISSUE THREAD

**Issue by XizzoR** [CERT-BDF/TheHive#287]
### Request Type

Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu Server 16.04.3
| TheHive version / git hash   | 2.12.1, hash of the commit
| Package Type              | Binary
| Browser type & version    | Google Chrome

### Problem Description
Message "A client error occurred on GET /docs : Resource not found by Assets controller" occurs when clicking on "help" in user section or just by redirecting to THEHIVE_ADDR:THEHIVE_PORT/docs

### Steps to Reproduce
1. Login to TheHive (doesn't matter if admin acc or not) 
2. Click on "Help" option from dropdown menu which represents a user section (most upper right corner) or just redirect to THEHIVE_ADDR:THEHIVE_PORT/docs
3. Profit

### Possible Solutions
Sorry, dunno.

### Complementary information
There are no errors on terminal while running an instance of TheHive

**Comment by hunsaker** [comment]
This is happening on the docker instance as well please update

**Comment by hunsaker** [comment]
<img width="904" alt="screen shot 2017-08-25 at 12 45 21 pm" src="https://user-images.githubusercontent.com/16806380/29728011-7234676e-8993-11e7-940e-8a951069fc94.png">

**Comment by nadouani** [comment]
Hi guys, sorry for this issue, we did it badly.

We were hoping to ship TheHive with a documentation content, but for now we don't have it, and we forgot to remove that menu item. 

Please refer to https://github.com/CERT-BDF/TheHiveDocs for documentation.

Thanks
