### ISSUE TITLE
Observable List doesnt show Report availables

### ISSUE THREAD

**Issue by ST2Labs** [CERT-BDF/TheHive#288]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Windows10
| TheHive version / git hash   | 2.12.1
| Package Type              | Binary
| Browser type & version    | Mozilla Firefox 55.0.2 64 bits

### Problem Description
List observables doesn't show "report available" when I ran Cortex Analyzers and doesn't update.

### Steps to Reproduce
1. Add observables
1. Run Analyzers
1. Nothing in "Observable List"

Cortex Engine: 1.1.3

I would like to "show" observable "labels" fill up by Analyzers into "observable list" to avoid have to click in observable to show it.

![image](https://user-images.githubusercontent.com/9781565/29620964-b423d1fc-881f-11e7-9f12-172055a60b1c.png)

This screenshot show | Analyzer executed with "custom labels"
![image](https://user-images.githubusercontent.com/9781565/29620977-bed6fda4-881f-11e7-829a-3717fe9ec310.png)

**Comment by nadouani** [comment]
Hello,

can you please run any analyzer from thehive and go to cortex's UI, and get the `summary`of that report?

I want to double check that your analyzers generate the right summary

**Comment by ST2Labs** [comment]
OK !

**Run My Analyzers > Cymon.io Connect**

![image](https://user-images.githubusercontent.com/9781565/29621676-bafbfeda-8821-11e7-941a-eb7c21644504.png)

`Summary` 
![image](https://user-images.githubusercontent.com/9781565/29621704-cd669954-8821-11e7-88e8-4569b680aad6.png)



**Run the Analyzers OTXQuery_1_0** 
`summary`
![image](https://user-images.githubusercontent.com/9781565/29621748-ec0ec9bc-8821-11e7-9fac-ca5af9d8771b.png)

**Comment by nadouani** [comment]
Are you sure your analyzers are up-to-date? same question for `cortexutils`pip library?

**Comment by ST2Labs** [comment]
Hi,

I think so !

![image](https://user-images.githubusercontent.com/9781565/29621951-6bf4638a-8822-11e7-8d37-d89edf4cbb72.png)

**Comment by nadouani** [comment]
So, you've just upgraded `cortexutils` could you please rerun the the analysis above and show me the summary again?

**Comment by ST2Labs** [comment]
OK

![image](https://user-images.githubusercontent.com/9781565/29622271-3fa96e50-8823-11e7-9b91-7546f2782f1f.png)

![image](https://user-images.githubusercontent.com/9781565/29622295-51c30bc8-8823-11e7-81cf-e7053a0289b4.png)

![image](https://user-images.githubusercontent.com/9781565/29622311-5c041b0e-8823-11e7-911b-c78bc3281e85.png)

**Comment by ST2Labs** [comment]
OK, 

I just check "version" on OTX Analyzers and I have v1.0 when last is v2.0 |

I going to update Analyzers ! But I don't know why my own Analyzer doesn't work !

Thanks in advance !

**Comment by nadouani** [comment]
We try to make the community aware of any change after every release on our blog, so you might find interesting information there. https://blog.thehive-project.org/

For your own analyzer, you can take a look to the analyzer we've wrote and update yours based on that. We are currently preparing a "How to write an analyzer" guide that could help.

**Comment by ST2Labs** [comment]
Hi, 

I just update "Cortez Analyzers" from https://github.com/CERT-BDF/Cortex-Analyzers but !! Observable list doesn't show "reports avaiables"

Screenshots >

![image](https://user-images.githubusercontent.com/9781565/29625249-7e8372c6-882b-11e7-8d08-16e17f005c7d.png)

**MaxMaind_3.0**
![image](https://user-images.githubusercontent.com/9781565/29625285-901e104a-882b-11e7-98d0-d42f2ec1b36b.png)

I haven't summary data from "MaxMind Analyzers v3.0" (update) then .. I don't know how to trace the problems.

Thanks in advance

**Comment by ST2Labs** [comment]
Hi, 

I solved it.

I have problem with `pip install cortextutils --upgrade` because I'm using python 2.7.12 and pip is python 3.5.

Solved:

> `pip2.7 install cortexutils --upgrade`

Thanks ! Now Obsevable list show "reports available"

![image](https://user-images.githubusercontent.com/9781565/29713803-9817a984-89a0-11e7-83bd-1683300fdc20.png)

**Comment by saadkadhi** [comment]
Solved after a Cortexutils upgrade by the user.
