### ISSUE TITLE
Changeable case owner

### ISSUE THREAD

**Issue by derDuffy** [CERT-BDF/TheHive#30]
### Request Type
Feature Request

### Description
The possibility to change the case owner would it make easier to align with  internal incident processes and therefore increase adoption of the hive.
Basically the same option exists for tasks already.

**Comment by mfosse71** [comment]
One comment though, who(which role) should have this possibility? A dispatcher role, In my case I would use the "on-call" person I think

**Comment by derDuffy** [comment]
If there will be a role concept implemented I would suggest to build it in such a way that the permissions for each role can be assigned individually by a admin role. As there are no such roles right now I would stick with the principle that every write user can change this.
