### ISSUE TITLE
Add health check in status API

### ISSUE THREAD

**Issue by To-om** [CERT-BDF/TheHive#306]
### Request Type
Feature Request

### Work Environment
TheHive <= 2.12

### Problem Description
TheHive should provide information on its health and on the state of connections to ElasticSearch, Cortex and MISP (if configured)

**Comment by romans8** [comment]
Any word on Cortex?

**Comment by rithgan** [comment]
> Any word on Cortex?

Hi, were you able to find anything on cortex?
