### ISSUE TITLE
Run observable analyzers through API

### ISSUE THREAD

**Issue by srilumpa** [CERT-BDF/TheHive#308]
### Request Type
Feature Request

I haven't seen it documented and, from my poor understanding of scala, I haven't seen it implemented. It would be a very nice addition to be able to run analyzers on all or part of the artifacts of a case. It could be done through the following endpoints:

| method | URI | comment
|----|---|---
| GET | /api/case/:caseId/artifacts/analyze | Run analyzers on all artifacts of the case 
| GET | /api/case/:caseId/artifacts/:actifactId/analyze | Run analyzers on on single artifact

Two parameters could be passed through the URL:
* analyzerType: type (i.e. class) of analyzer to be ran
* analyzerName: instance name of the analyzer to be ran
If none of those two are defined, then all analyzers will be ran.

**Comment by Xyrodileas** [comment]
Hello,
The previous request was closed, but I didn't find a way to run all the analyzers for a case or an observables within a case.
The merging commit only add the capability to trigger a job via an artifactID and analyzerID, which is not exactly what was requested.
Does a feature similar to what describe srilumpa exist within TheHive's API ?
Thanks !
