### ISSUE TITLE
Statistics on a per case template name / prefix basis

### ISSUE THREAD

**Issue by derDuffy** [CERT-BDF/TheHive#31]
### Request Type
Feature Request

### Description
One can already display statistics data based on tags. However tags can be changed by users. 
Therefore it would be helpful to be able to filter the statistics based on either the case template name or the prefix - possibly both.
This would allow for some fine granular reporting and also make sure that users can not simply remove / change the basic "categories" used to generate statistics.

**Comment by nadouani** [comment]
Actually, when you create a case from a template, we don't keep the information (about the template identifier) in the case data, so we aren't able to find the list of cases created via a given template. 
In other words, in the data model, there is no relation between a case and it's original template.

**Comment by saadkadhi** [comment]
Given @nadouani's reply, I will close the feature request. @derDuffy if you've got some strong use cases that won't be satisfied by #36 feel free to reopen this one.

**Comment by derDuffy** [comment]
@saadkadhi if the tags can be made sticky to the template, i.e. they cannot be removed from the template by non-admin users then this will totally work for my use case. Thanks 👍
