### ISSUE TITLE
Remove the deprecated "user" property

### ISSUE THREAD

**Issue by nadouani** [CERT-BDF/TheHive#316]
### Request Type
Enhancement

### Problem Description
The UI is still displaying a deprecated field `user` that has been replaced by `owner` on entities like `case`, `task` and `task_log`.

This issue aims to make a clean up and introduce a better consistency through the UI's base code

**Comment by To-om** [comment]
Attribute "user" has been removed by the issue CERT-BDF/elastic4play#33
