### ISSUE TITLE
Deleted cases showing in statistics

### ISSUE THREAD

**Issue by mthlvt** [CERT-BDF/TheHive#317]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | n/a |
| OS version (client)       | n/a|
| TheHive version / git hash   | 2.12.1 |
| Package Type              | Docker |
| Browser type & version    | n/a|

### Problem Description
Deleted cases still visible in the statistics page

### Steps to Reproduce
1. create a case with a unique tag to identify it
2. delete it via the API
3. filter the stats view with the unique tag
4. see that the statistics show the case even though it is deleted.

### Complementary information

Case status is : 'Deleted'
![image](https://user-images.githubusercontent.com/11675835/30744366-134a5cfc-9fa2-11e7-85fd-30668fdeea0a.png)

Case shows in Statistics:
![image](https://user-images.githubusercontent.com/11675835/30744232-72af0e78-9fa1-11e7-8d47-cdcd3422d6ef.png)

**Comment by nadouani** [comment]
Thanks @mthlvt thats fine. The fact is that deleting a case is not a feature in TheHive and deleting it currently is just a workaround to make it hidden on the cases list. But I agree this is not clean.

We will consider adding  feature to support a case and take that status into account everywhere ;)

**Comment by nadouani** [comment]
The new dynamic dashboards feature will allow you to filter the cases you want to see. In this case you will be able to exclude deleted case.

Closing this request.
