### ISSUE TITLE
OTX Analyzer

### ISSUE THREAD

**Issue by ecapuano** [CERT-BDF/TheHive#32]
### Feature Request

I am currently working on an analyzer that will utilize the AlienVault OTX API to enhance the following observables, `ip`, `file`/`hash`, `domain`, `url`. 

I expect to have it wrapped up in a day or two. 

Moving forward, I will sharpen my skills with Hippocampe to try and leverage a single system for these tasks.

**Comment by ecapuano** [comment]
PR https://github.com/CERT-BDF/TheHive/pull/39 submitted.

**Comment by saadkadhi** [comment]
Thanks @ecapuano. We will be evaluating it shortly.

**Comment by nadouani** [comment]
This feature in now included within 2.9.2 release
