### ISSUE TITLE
Keep the alert date when creating a case from it

### ISSUE THREAD

**Issue by srilumpa** [CERT-BDF/TheHive#320]
### Request Type
Feature Request

We are automatically creating alerts and cases through the API. When we create an alert we set up its date with the data coming from our monitoring tools. Unfortunately, that date seems to be lost when we create a case from those alerts (using the `/api/alert/${alert_id}/createCase`) since the date of the case is its creation date.

How can we keep the alert date in the case? That information is rather critical when processing a case.

I think it could be really useful to keep somewhere in the case the date of the alert linked to it. Even more, since cases could be linked to several alerts (through merged cases), a good addition would be to have access to min date and max date or, even better, a timeline created from the alerts date.

In the mean time, we will probably try to use a case custom field to store that information.

Best regards

**Comment by saadkadhi** [comment]
Thanks @srilumpa. It makes perfect sense to carry the alert date over to the case when it is created, for ex. in its description. We will try to implement this missing and rather important functionality in Cerana (3.0).

**Comment by nadouani** [comment]
The alert's date could be in fact set as the case's `startDate` field
