### ISSUE TITLE
Option to disable misp-modules

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#323]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 8.9
| TheHive version / git hash   | 2.13.1
| Package Type              | DEB

### Problem Description
Currently misp-modules can only completely or not disabled.
It would be helpfull to be able to disable selected modules.
Especially if some modules makes no sense or do not work as they should.

**Comment by saadkadhi** [comment]
Hi @crackytsi. This feature request is related to Cortex, not TheHive. I opened [issue #44](https://github.com/CERT-BDF/Cortex/issues/44) on the Cortex repository.
