### ISSUE TITLE
caseTemplate should be kept when creating a case from a template

### ISSUE THREAD

**Issue by srilumpa** [CERT-BDF/TheHive#325]
### Request Type
Feature Request

Currently, when a case is created from a caseTemplate, there is no reference kept between the case and the template. Keeping that link would be useful for:
* statistics (case repartition per template)
* troubleshooting (why some tasks are linked to a case, or not...)
* additional processing (manual or not) external to TheHive

**Comment by nadouani** [comment]
Hi @srilumpa this topic has been already though of, but we decided to make use of tags instead of keeping the information about the name of the case template, a case is based on.

We could reconsider that, but using a tag with a case template can help solving the 3 points you listed above.

**Comment by srilumpa** [comment]
That is what we are doing but it relies on the fact that the guy who created/updated the caseTemplate tagged it properly and we already have a lot of tags so having one less would have left the UI lighter.

But I understand your point and we will keep it that way.

Thank you.

**Comment by nadouani** [comment]
We are welcome to do it if some other people ask for it, it's not a big deal.
