### ISSUE TITLE
HTTPS GUI for TheHive

### ISSUE THREAD

**Issue by pottapitot** [CERT-BDF/TheHive#334]
### Request Type
Feature Request

Hi,

It would be great to an option to have the interface of TheHive use https rather than http  or provide an option to select the same during the setup ( initially using a self signed certificate and TLSv1.2).  It would save time in configuring a reverse proxy.

**Comment by nadouani** [comment]
Hello,

TheHive is based on PlayFramework which allow you to **configure** your application to be served over HTTPS. (https://www.playframework.com/documentation/2.6.x/ConfiguringHttps#production-usage-of-https)

That said, we recommend using a Reverse Proxy for that (which is not a big deal).

Thanks
