### ISSUE TITLE
"Question Mark" circle next to the custom field name

### ISSUE THREAD

**Issue by pottapitot** [CERT-BDF/TheHive#336]
### Request Type
 Feature Request

Is it possible to have a "question mark" symbol (like a small question mark in a circle) next to the custom field name so that the user can know he can click on the question mark to get the "description" popup on the field. 

In my case I wasn't aware you will see the "description" until I accidentally moved the mouse over the custom field "title"

**Comment by nadouani** [comment]
Hello,

for now, to be consistent with rest of the UI, we display descriptions and 'more details' using tooltips, and hover.

Thanks
