### ISSUE TITLE
Prevent deletion of tasks configured in custom case templates

### ISSUE THREAD

**Issue by pottapitot** [CERT-BDF/TheHive#338]
### Request Type
Feature Request

Hi,

Is it possible to disable the tasks configured in custom case templates and them to be edited only from the templates section. We want to prevent analysts from accidentally deleting tasks.

**Comment by saadkadhi** [comment]
Hi @pottapitot. We are unlikely to implement such a feature request. Tasks can be very easily recreated once they have been deleted.

**Comment by pottapitot** [comment]
@saadkadhi .. Oh ok.. it was because we wanted to create fixed case templates for each incident category we would create. And possibly have version control for the case template to keep track of any changes to the template. It would be difficult to keep track if someone were to delete any of the tasks in any of the cases. If we were to later come back to the case and find the task missing, the logs of the task would be lost.
If not this is there any other way to prevent deletion of tasks by a regular analyst?

**Comment by saadkadhi** [comment]
While I get your use case, this would be a way too precious waste of development time for a FOSS project such as ours. 

Implementing version control on case templates and trying to further lock down users from easily recoverable mistakes is not the way we stir TheHive and its future. We'd rather let teams educate themselves on how to use the platform.

Currently and in the foreseeable future, the only way to prevent deletion of tasks by a regular analyst is to tell them not to. Regular awareness sessions and trainings is your best option. And if you don't trust your analysts to do the right thing and learn from their mistakes, then maybe you should consider parting ways with them :-)

That being said, feel free to submit a PR and we'll consider it in due time.

**Comment by pottapitot** [comment]
@saadkhadi No problem. Thanks alot for the input.
