### ISSUE TITLE
Storing events in alerts/cases

### ISSUE THREAD

**Issue by srilumpa** [CERT-BDF/TheHive#340]
### Request Type
Feature Request

Hi,

Alerts are triggered from logs injected in our SIEM systems and then imported in TheHive to be treated by our analysts. Unfortunately, by doing so we lose the links between the alert and its related logs, making hard for the analysts to trace exactly what happened and to find back the timeline of events.

We are thinking of compiling all logs for an alert in a text file and uploading it as an artifact of the alert but this feels more as a hack than anything.

Will it be possible to include logs import alongside the alert creation?

Best regards.

**Comment by nadouani** [comment]
Hello, what do you mean by alert logs?

Today, there is a link from the alert to the case (the caseId is one of the alert attributes once imported)

**Comment by srilumpa** [comment]
Hi,

I mean the alert triggered by a SIEM system, a tool meant to collect and correlate logs/events from various devices on a network (servers, security equipments, etc). A SIEM will trigger alerts based on one or multiple logs matching some conditions (for example several failed authentications for the same user across several equipments of the platform).

Once one of those alerts is triggered by the SIEM, we are importing it into TheHive as an alert to be treated by our analysts if needed. Unfortunately, we are not currently able to import the logs in TheHive. To understand why the alert has been triggered, we need to log in our SIEM system, find back the original alert and then retrieve the logs. Those logs/traces (external from TheHive) are not artifacts per say but having them when you are analyzing the alert are more than helpful.

TheHive is an awesome tool but being able to attach the events that triggered alerts would make possible end-to-end analysis in TheHive.

**Comment by nadouani** [comment]
Ok I see what you mean: alert logs = the SIEM alerts that triggered the creation of an alert on TheHive.

Well, these could be set as:
1/ part of the alert desciption (use a Markdown pre format syntax), once imported it will be set as case description.
2/ alert artifact of a custom datatype, let's say, `siem_log`

A more specific solution could break the generic model behind the alerting framework: not all alerts need this type of logs for example.

I hope this is a viable solution for you. If someone else has another suggestion, it will be welcome

**Comment by srilumpa** [comment]
Ok, we'll include them in the description in a pre-formatted section.

**Comment by rver21** [comment]
I recommend you one of the best security product that provide SIEM facilities. LTS Secure Security Information and Event Management (SIEM), is a technology that provides real-time analysis of security alerts generated by network hardware and applications. For more information about this product [Click Here](http://bit.ly/ltsssecure)
