### ISSUE TITLE
[Minor] Add user dialog title issue

### ISSUE THREAD

**Issue by saadkadhi** [CERT-BDF/TheHive#345]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | macOS
| TheHive version / git hash   | 2.13.1
| Package Type              | DEB
| Browser type & version    | Chrome 62

### Problem Description
This is obviously a really minor issue. When an admin creates a new user, the dialog that is displayed is titled **Add user** but as soon as the admin types a char in the **Login** field, the dialog's title changes to **Update user** which is misleading.

### Steps to Reproduce
1. Log in as an admin
1. Go to **Admin > Users**
1. Click on **Add User**
1. Type a char in the **Login** field
1. See the dialog's title change from **Add user** to **Update user**

### Complementary information
Dialog after the **Add user** button is clicked:
<img width="899" alt="screen shot 2017-10-19 at 06 42 59" src="https://user-images.githubusercontent.com/2852427/31754647-68285cea-b499-11e7-91ce-43ead3a157cb.png">

Dialog after a char is typed in the **Login** field:
<img width="899" alt="screen shot 2017-10-19 at 06 43 10" src="https://user-images.githubusercontent.com/2852427/31754659-82dea0f8-b499-11e7-995b-83e97dc17871.png">

**Comment by nadouani** [comment]
This is a very minor change, moving to Cerana
