### ISSUE TITLE
Incorrect stats: non-IOC observables counted as IOC and IOC word displayed twice

### ISSUE THREAD

**Issue by saadkadhi** [CERT-BDF/TheHive#347]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | macOS
| TheHive version / git hash   | 2.13.1
| Package Type              | DEB
| Browser type & version    | Chrome

### Problem Description
In the **Case > Observables** tab, clicking on **Stats** will show in the **Observables as IOC** table:
- number of non-IOC observables with an IOC label
- number of IOC observables with the same label

Duh!

### Steps to Reproduce
1. Create a case
1. Add 4 observables 
1. Flag 1 as IOC
1. Click on **Stats**
1. Look the results in the **Observables as IOC** table
1. Go insane

### Possible Solutions
Do the math George.

### Complementary information
<img width="1072" alt="screen shot 2017-10-19 at 09 37 03" src="https://user-images.githubusercontent.com/2852427/31759471-cc35046e-b4b1-11e7-9084-ab78b629039a.png">

**Comment by nadouani** [comment]
This is a regression introduces by the move to ES5. In fact the result of an aggregation by a boolean field has a new structure, which breaks the behavior of the observable by IOC flag's stats panel.
