### ISSUE TITLE
TAGs based on taxonomies

### ISSUE THREAD

**Issue by mfosse71** [CERT-BDF/TheHive#35]
Looking at MISP as well, there you have the possibility to tag Events in different categories, this is an excellent idea and I propose that this is implemented into thehive
For example in the MISP you can use the VERIS taxonomy, this is really useful for adding tags for cases to show more or less the details around the case, you can tag with country, type of enviroment, source of incident, impact, what kind of actor, insider etc. etc. 

I suggest these gets implemented as tags in thehive, also that TLP, VERIS and MISP at least are implemented, if you like to make this work for the same organisations using MISP, then consider being able to use all the same taxonomies as them

### Request Type
Feature Request

**Comment by saadkadhi** [comment]
Thank you @mfosse71 for this feature request. This looks similar to #55. I suggest we close this one and keep track of your request in #55

**Comment by saadkadhi** [comment]
We will track this in #55.
