### ISSUE TITLE
[Bug] Merging an alert into case with duplicate artifacts does not merge descriptions

### ISSUE THREAD

**Issue by BrevilleBro** [CERT-BDF/TheHive#357]
# Merging an alert into case with duplicate artifacts does not merge descriptions

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 2.13.1
| Package Type              | From source

### Problem Description
Currently working on a feature which allows bulk merging of alerts into cases. However, if a an alert tries to merge with a case which already has all the artifacts listed in the alert, the description of the alert is not merged.
 
### Steps to Reproduce
1. Using the API, attempt to bulk merge alerts with different case descriptions, but same artifacts (i.e., using the /merge/ API)
1. Notice in the error logs the error `[warn] s.AlertSrv - Create artifact error org.elastic4play.ConflictError: Artifact already exists` is present
1. Notice in the Case the alerts merged into, not all the case descriptions were merged. For some reason some may be merged, while others are not.

### Possible Solutions
Allow merging of multiple alert descriptions to a case even if there are duplicate artifacts within the case.

### Complementary information
Error message present in log files:
`[warn] s.AlertSrv - Create artifact error org.elastic4play.ConflictError: Artifact already exists`

**Comment by saadkadhi** [comment]
Thanks @BrevilleBro. We will look at it as soon as we can.

**Comment by BrevilleBro** [comment]
Much appreciated.

**Comment by BrevilleBro** [comment]
@To-om , thanks for your work on this. I am still getting the error when trying to merge alerts with duplicate artefacts, but different descriptions.
`[warn] s.AlertSrv - Create artifact error
org.elastic4play.ConflictError: Artifact already exists
`
