### ISSUE TITLE
alert is not generate new case 

### ISSUE THREAD

**Issue by sehot** [CERT-BDF/TheHive#360]
Hi
I start working with the training enviromaent and it's look great , i have 1 problem:
I send alerts from my SIEM , the alert is received but it is not  generate new case according to the "CERT" template , (i create CERT template)

this is the POST request(python):

```
import requests
import json

headers = {
    'Authorization': 'Bearer XXXXXXXXXXXXXXXXXXXXXXXXXX',
    'Content-Type': 'application/json',
}

data = {"title": "test 10",
  "description": "alert description",
  "type": "external",
  "source": "instance1",
  "sourceRef": "alert-ref",
  "severity": 3,
  "tlp": 3,
  "_id":'999999999999999167',
  "caseTemplate": 'CERT',
        }

a=requests.post('http://8.200.60.230:9000/api/alert', headers=headers, data=json.dumps(data))
```
What am i missig ?

**Comment by jeromeleonard** [comment]
Hi,

You may want to have a look at thehive4py lib.  You can install it with
pip. It is intended to help using the API.
You can find the repo here : https://github.com/CERT-BDF/TheHive4py
An example of program that generates alerts can be find here  :
https://github.com/CERT-BDF/TheHive4py/blob/master/samples/test-alert-create.py

Particularly, the library contains everything to create your data object ;
it should be an 'Alert' defined in thehive4py.models. Once the 'Alert'
object is defined you just have to call create_alert('Alert')
from thehive4py.api and everything should be fine.

J.

**Comment by sehot** [comment]
Hi,

The Alert is created as it should but i want also to generate a new case autmaticlly , as far as i understand to do that i have to add the `"caseTemplate":`  field in the post request , i did that but still no case generate :( 

any idea ?

**Comment by Rolinh** [comment]
Hi @sehot,

Adding the `"caseTemplate"` field only means that if the alert is converted to a case, then the case will be created according to the template.

If you want to create a case directly, you will have to do a `POST` request on the `/api/case` route. @jeromeleonard suggested you use TheHive4py and I believe this is a good advice. If you can't use python however, doing a POST request with appropriate body is no big deal anyway (curl, powershell, ...).
Just head to the [API documentation](https://github.com/CERT-BDF/TheHiveDocs/tree/master/api), especially [this section](https://github.com/CERT-BDF/TheHiveDocs/blob/master/api/case.md#create-a-case), and start coding/scripting.

**Comment by nadouani** [comment]
The creation of an alert doesn't automatically generate a case.
If you need a case, then use the case API, or use the UI to import an alert into a case.

Nabil
