### ISSUE TITLE
Search case with API - QUESTION

### ISSUE THREAD

**Issue by sehot** [CERT-BDF/TheHive#361]
**QUESTION**

Hi
how can i search for specific case with API request ?
what should i send in the body request ?

**Comment by nadouani** [comment]
Hello @sehot,

Could you please join the [Gitter channel](https://gitter.im/TheHive-Project/TheHive) to ask questions, or send and email to the user group as described at https://github.com/CERT-BDF/TheHive#community-discussions.

Issues should be used to submit bugs or feature requests.

Yes, the search API can be used to "search" for cases, so it depends on what type of criteria you want use to find the searches you want.

Nabil
