### ISSUE TITLE
Set task assignee in case template

### ISSUE THREAD

**Issue by ralliauto** [CERT-BDF/TheHive#362]
Hi

When creating a case template you can add tasks but not set assignee. It would be of great help if there is an option to predefine assignee if you already know your workflow and who will be taking on the tasks. 
Otherwise you will create a template to speed up the workflow, but still have to take extra steps to go and set an assignee.
In addition, the possibility to set/change assignee without opening the task, e.g a field that actively searches from the list of users as you type, would greatly increase UX.

Hopefully this subject is relevant to others too and the problem isn't just in my lack of knowledge.
Best regards!

**Comment by woifi** [comment]
That would be a great feature for us as well!

**Comment by nadouani** [comment]
This is an interesting feature request, I agree
