### ISSUE TITLE
Alert id should not be used to build case title when using case templates

### ISSUE THREAD

**Issue by srilumpa** [CERT-BDF/TheHive#364]
### Request Type
Feature Request

Currently, the id of the alert is used to prepended to the alert title when creating the case using the "createCase" API command with a case template. This can generate case titles quite cryptic depending of what is used as alert ids (combination of timestamps, file hashes, hostnames, usernames, etc).

Could it be possible to remove those ids from the title ? A solution would be to have a checkbox in the case template to toggle the use of alert id to generate the case title.

**Comment by To-om** [comment]
The ID of the alert has been removed by 89413ff74a9bdc8d9da0f0f42d18e8128bef392f

**Comment by srilumpa** [comment]
From the name of the modified file in the commit, this is applying only to cases created from MISP events, isn't it? My issue was more global and was wondering if it was possible not to display  the alert id in the case title for all type of cases or according to a setting in a caseTemplate.
