### ISSUE TITLE
Statistics based on Tags

### ISSUE THREAD

**Issue by mfosse71** [CERT-BDF/TheHive#37]
I propose that it should be possible to create statistics based on tags

### Request Type
Feature Request

**Comment by nadouani** [comment]
Hello, could you please tell us a bit more about this requirement? Is it something different from what you are already able to do within the "Statistics" Page?

Note that, in the current version, you can filter the cases by one or several tags in the Statistics page.

If it doesn't satisfy you needs, please feel free to reopen this issue and explain a bit more what you think is missing about tags and stats.

Thank you
