### ISSUE TITLE
MISP Event Export Error

### ISSUE THREAD

**Issue by treed593** [CERT-BDF/TheHive#387]
# Error exporting events to MISP

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Mac osX 10.12.6
| TheHive version / git hash   | 3.0
| Package Type              | DEB
| Browser type & version    | Chrome 62.0.3202.94

### Problem Description
When trying to export events to MISP I receive an error

Failed to export the following observables

### Steps to Reproduce
1. Open case with observables
2. Click "Share"
3. Click "Export" next to MISP instance

### Complementary information
`2017-12-06 17:05:15,660 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-47 - Illegal request, responding with status '400 Bad Request': Illegal request-target: Invalid input '[', expected segment, '/', '?' or 'EOI' (line 1, column 49): /api/connector/misp/export/AWAULYFEgB5b8FcH__HR/[object%20Object]`
![screen shot 2017-12-06 at 12 08 07 pm](https://user-images.githubusercontent.com/6807466/33674717-479c3aa4-da7e-11e7-9140-d46cd41283c5.png)

**Comment by treed593** [comment]
![screen shot 2017-12-06 at 12 09 54 pm](https://user-images.githubusercontent.com/6807466/33674744-658e629e-da7e-11e7-88ea-4be060549f2d.png)

**Comment by nadouani** [comment]
Thanks @treed593 for finding this regression. We will release a hot fix in the upcoming hours.
