### ISSUE TITLE
Question: Push tasks from The Hive into JIRA

### ISSUE THREAD

**Issue by jezkerwin** [CERT-BDF/TheHive#388]
Hi All,
I'm looking at implementing The Hive for my SOC team. Our IT operations uses JIRA for task management and was curious if it would be possible to have a task relating to a Hive case created, that would then push that task to JIRA for IT operations to action.

A specific example would be if a malware infection tasks place. A case would be created in The Hive for the SOC analyst to work on. One of the tasks might be to get the local desktop support team to isolate their workstation off network. Because IT operations use JIRA and wouldn't have access to The Hive, it would be great if there was an automation that could push a Hive task to JIRA.

Cheers.

**Comment by nadouani** [comment]
Hello @jezkerwin 

The easiest way to do that is to declare a Webhook on TheHive. This webhook should listen to case creations, and based on the case type (probably a template + a tag), call the JIRA api to create the JIRA issue.

Please refer to https://github.com/CERT-BDF/TheHiveDocs/blob/master/admin/webhook.md

Let me know if this is clear, or reopen the case.

Cheers.

**Comment by jezkerwin** [comment]
Yep, that makes sense. Could it be limited to just a task? In my example I'd only want specific tasks of a case sent to Jira?

**Comment by nadouani** [comment]
Webhooks receive all the changes made on TheHive, you can listen to events of type Creation of Task and do whatever you want.

**Comment by jezkerwin** [comment]
Sounds exactly what I want.
Thanks.

**Comment by jezkerwin** [comment]
Follow up question. Is there more documentation to the webhooks about how to configure, what can be configured in the webhook or is what is contained at the following link is all there is?

https://github.com/CERT-BDF/TheHiveDocs/blob/master/admin/webhook.md
