### ISSUE TITLE
Cortex not connecting

### ISSUE THREAD

**Issue by treed593** [CERT-BDF/TheHive#389]
# Cortex not connecting

### Request Type
Bug

### Problem Description
After updating to 3.0.1 from #387 Cortex is no longer connecting to our instance of The Hive 

### Steps to Reproduce
1. Update to 3.0.1
2. Cortex is no longer working

**Comment by treed593** [comment]
@nadouani ... fyi

**Comment by nadouani** [comment]
Well, what's happening here? :)

**Comment by saadkadhi** [comment]
@treed593 if there's a new regression we really need to know about it. Thank you for any information you might provide. Also, when possible, try discussing problems with us on our [Gitter channel](https://gitter.im/TheHive-Project/TheHive) and we'll ask you to open an issue if we confirm it's a bug. Thanks.

**Comment by nadouani** [comment]
No @saadkadhi everything works fine. This issue is not valid.
