### ISSUE TITLE
Audit trail per case

### ISSUE THREAD

**Issue by dotwayland** [CERT-BDF/TheHive#391]
### Request Type
Feature Request

An audit record for each case indicating actions that have been performed against it and the time the action was performed. Possible transactions of interest: time opened, time closed, executor of action (was it a person, a service account, automated process, etc)

**Comment by nadouani** [comment]
This wi what we call "Case Timeline" https://github.com/CERT-BDF/TheHive/issues/84

It's basically a Flow with all the details, not only the last 10 elements
