### ISSUE TITLE
Tags not saving when creating observable.

### ISSUE THREAD

**Issue by AdventuresInMalware** [CERT-BDF/TheHive#4]
# Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template.

### Request Type
(remove everything that does not apply)
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.10
| OS version (client)       | Ubuntu 14.04
| TheHive version / git hash   | Unsure
| Package Type              | Binary
| Browser type & version    | Chrome

### Problem Description
When adding a new observable to an incident the tags are not saved.

### Steps to Reproduce
1. Create Case
2. Create Observable
3. Add Tags
4. Save Observable.

**Comment by saadkadhi** [comment]
Thank you @AdventuresInMalware for reporting this issue. It is indeed a bug and we will be fixing it very soon.

**Comment by jeromeleonard** [comment]
As a workaround and waiting for the fix, you can create observables with description, and after that, select them in the list, click on "Action" menu and select "Add tag".
![screenshot 2016-11-08 16 22 41](https://cloud.githubusercontent.com/assets/10532879/20104850/d4466b1c-a5cf-11e6-9a29-fb87ef5074b0.png)
