### ISSUE TITLE
Ability to add tags to tasks

### ISSUE THREAD

**Issue by jezkerwin** [CERT-BDF/TheHive#401]
Is there the ability to add tags to tasks that may or may not be different to the case itself?

Are there plans to introduce a feature if it doesn't exist?

Thanks.

**Comment by saadkadhi** [comment]
_Q: Is there the ability to add tags to tasks that may or may not be different to the case itself?_
A: No

_Q: Are there plans to introduce a feature if it doesn't exist?_
A: No. What would be the use case(s)? Adding tags to tasks besides cases and observables would probably add clutter to the interface and be confusing. Tasks are meant to be associated to a case. Hence distinguishing between task-level tags and case-level tags have limited value in my opinion.

**Comment by jezkerwin** [comment]
Thanks for the response. 
The use case I'm thinking is like the following.
An incident the SOC team is dealing with, have identified different tasks that will be handled by different teams (ie. Network, Server, Desktop, etc). Those teams don't necessarily need to see the contents of the entire case, just their individual tasks (ie. block IP address on external firewall). Having a tag could make it easier for automation tasks to process actions based on the tag.
