### ISSUE TITLE
Statistics by Template

### ISSUE THREAD

**Issue by megan201296** [CERT-BDF/TheHive#49]
# Statistics by Template    
### Request Type
Inquiry / Feature Request

### Problem Description
Not sure if this exists and I can't find it or if it would be a feature request. One of the most useful categories to track for our team on the statistics page (second to the custom metrics) would be cases "by Template". i.e., we opened 5 cases using the "phishing template", 4 "malware" cases, etc. This would allow us a great overview to the types of incidents we responded to without the manual work of counting each time. Should be simple to track under stats because of the "headers" appended to each case title. Let me know if there is a way to do this and I am just missing it.

**Comment by nadouani** [comment]
Hi, did you assign any tags for cases based on your templates?

Example: did you tag your "Phishing" cases with a "phishing" tag? If yes, the you can filter the statistics page with that tag

**Comment by megan201296** [comment]
Yep. I see that now. Thanks!

**Comment by nadouani** [comment]
I'll close this issue then.
