### ISSUE TITLE
chrome on os x - header alignment

### ISSUE THREAD

**Issue by JamesHabben** [CERT-BDF/TheHive#5]
# Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template.

### Request Type
(remove everything that does not apply)
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | , ubuntu, 
| OS version (client)       | os x 10.11.6
| TheHive version / git hash   | 2.9
| Package Type              | , Binary, 
| Browser type & version    | google chrome 54

### Problem Description
on the main page, the header for 'current cases' is hidden under the black header. Firefox shows header correctly.

### Steps to Reproduce
1. open page with chrome
2. visit open cases page

**Comment by nadouani** [comment]
Hi @JamesHabben,
This seems to be an issue related to the navigation bar that wraps on small screen resolutions.

Do you have any screenshot regarding that? I'm curious to see how that works fine on FF and not on Chrome.

Thanks
