### ISSUE TITLE
Unable to use SSL on AD auth

### ISSUE THREAD

**Issue by radix-radix** [CERT-BDF/TheHive#50]
### Request Type
Bug Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04.1 LTS
| OS version (client)       | Windows 7 x64
| TheHive version / git hash   |  thehive-2.9.0
| Package Type              | Binary
| Browser type & version    | Chrome 54

### Problem Description
Unable to authenticate with Active Directory if useSSL is true in auth.ad section - works if useSSL is false

### Steps to Reproduce
in /etc/application.conf  in auth.ad set useSSL = true

### Possible Solutions
My guess is that our AD SSL cert is not trusted by JRE. Tried adding our CA to the Java cacert keystore (/usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts) but it did not help. May not have done it corectly.

### Complementary information
**/var/log/syslog**
Nov 29 15:13:10 thehiveserver1 thehive[3159]: [#033[37minfo#033[0m] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:8080
Nov 29 15:13:52 thehiveserver1 thehive[3159]: [#033[31merror#033[0m] o.e.s.a.ADAuthSrvFactory$ADAuthSrv - AD authentication failure
Nov 29 15:13:52 thehiveserver1 thehive[3159]: javax.naming.CommunicationException: simple bind failed: my.domainnamewashere.com:636
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:219)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2788)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at javax.naming.InitialContext.init(InitialContext.java:244)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.validator.Validator.validate(Validator.java:260)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: #011at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
Nov 29 15:13:52 thehiveserver1 thehive[3159]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**application.conf**
auth {
    type = [local,ad]
    ad {
        # Domain Windows name using DNS format. This parameter is required.
        domainFQDN = "my.domainnamewashere.com"

        # Domain Windows name using short format. This parameter is required.
        domainName = "domainnamewashere"

        # Use SSL to connect to domain controller
        useSSL = true
    }

**Comment by To-om** [comment]
Hi,
You need to create a JKS truststore using [keytool](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html). This truststore must contain the certificate authority of AD certificate (not directly the certificate).
Then add `-Djavax.net.ssl.trustStore=/path/to/your/truststore` parameter when you start TheHive (or put it in `JAVA_OPTS` environment variable before starting TheHive)

**Comment by radix-radix** [comment]
Thanks, that fixed it. I think this should be included in the Admin guide and/or the comments for auth.ad. Should I open a new feature request or can you convert this issue?

**Comment by nadouani** [comment]
Thanks @radix-radix, no need to open a new feature request for that, we will update the documentation and add more details about SSL config.

**Comment by To-om** [comment]
Add documentation in administrator's guide ([diff](https://github.com/CERT-BDF/TheHive/wiki/Administrator's-guide/_compare/b9da6239ef7bb887d5be2e2dd1d0770464bd373d...dd211ee98aaeba80d7e5a73e6587a9258ae31236))
