### ISSUE TITLE
Feature Request - Add observable statistics

### ISSUE THREAD

**Issue by To-om** [CERT-BDF/TheHive#71]
### Request Type
Feature Request

### Description
Add observable statistics:
  - count by type
  - count by ioc
  - count over time

each of them should be filtered by a tag.

**Comment by nadouani** [comment]
![screen shot 2017-01-09 at 13 25 48](https://cloud.githubusercontent.com/assets/21827/21766508/422e1966-d66f-11e6-8815-4b9316f97c96.png)
