### ISSUE TITLE
Error during bin/thehive

### ISSUE THREAD

**Issue by Hippolyteb** [CERT-BDF/TheHive#73]
## Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 2.x, hash of the commit
| Package Type              |  Binary

### Problem Description
Hello, my query " bin/thehive -Dconfig.file=/etc/thehive/application.conf " hangs after the line :
p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

Thank you

**Comment by To-om** [comment]
Hi,
Can you check if there is line in log file after "Listening for HTTP on /0:0:0:0:0:0:0:0:9000" ?
Can you post the output of the command "curl -v http://127.0.0.1:9000" ?
Is there error message in ElasticSearch output ?

**Comment by Hippolyteb** [comment]
Thanks for your answer, my problem is solved, it was necessary to open localhost: 9000 to unblock the situation.
However, when I restart my machine, I can not access TheHive

**Comment by mathgirl26** [comment]
I have the same issue. There is any line after "Listening for HTTP on /0:0:0:0:0:0:0:0:9000" in the log file.
The output of the comand "curl -v http://127.0.0.1:9000" is:
>About to connect() to 127.0.0.1 port 9000 (#0)
>  Trying 127.0.0.1...
>Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9000
> Accept: */*
> HTTP/1.1 303 See Other
> Location: /index.html
> Content-Length: 0
> Date: Wed, 18 Jan 2017 08:40:25 GMT
>Connection #0 to host 127.0.0.1 left intact

And I have any error message in ElasticSearch!

Thank you for your help!
