### ISSUE TITLE
Restart and no access

### ISSUE THREAD

**Issue by Hippolyteb** [CERT-BDF/TheHive#74]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 2.x, hash of the commit
| Package Type              | Binary

### Problem Description
When I restart my machine, I can not access TheHive

I have few logs like that :
[ERROR] from play.api.libs.crypto.cryptoConfigParser in main - The Application secret has not been set, and we are in prod mode. Your application is not secure
[ERROR]  from play.api.libs.crypto.cryptoConfigParser in main - To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret 

Is it related ?

Thanks

**Comment by To-om** [comment]
It is probably not an issue. For support please use support@thehive-project.org or open a discussion on our forum: https://github.com/CERT-BDF/TheHive#community-discussions
Regards
