### ISSUE TITLE
Analyzer registration failed

### ISSUE THREAD

**Issue by Hippolyteb** [CERT-BDF/TheHive#75]
### Problem Description
During the query bin/thehive .... , all the analyzers are in [error] 

why ?

In the gui i have this error :
-  An unexpected error occured: <class 'domaintools.exceptions.ServiceExcepetion' >: Empty API username    OR
- Missing VirusTotal Api key     OR
- Missing url for Hippocampe API
Thanks

**Comment by To-om** [comment]
It is probably not an issue. For support please use support@thehive-project.org or open a discussion on our forum: https://github.com/CERT-BDF/TheHive#community-discussions
Regards
