### ISSUE TITLE
Observables password hint does not reflect backend change

### ISSUE THREAD

**Issue by derDuffy** [CERT-BDF/TheHive#83]
### Request Type
Bug

### Problem Description
Changing the password for ZIP encryption is not reflected in the hint on the observables site.
The hint will still display "Zip are protected with password "malware"".

### Steps to Reproduce
1. Set datastore.attachment.password to something
2. Upload an observable
3. Try to download it and check the hint (the zip will actually be using the password set in step 1)

**Comment by nadouani** [comment]
Nice catch @derDuffy We will fix this in a 2.10.1 release. The 2.10.0 is already feature/bug freeze.

**Comment by derDuffy** [comment]
Thanks :)
