### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by eliebilly** [CERT-BDF/TheHive#89]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
(select Bug or Feature Request and **remove this part**)
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| TheHive version / git hash   | 2.x, hash of the commit
| Package Type              | Docker, Binary, From source
| Browser type & version    | If applicable

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. step 1
1. step 2
1. step 3...

### Possible Solutions
(keep this section if you have suggestions on how to solve the problem. **Otherwise delete it**)

### Complementary information
(add anything that can help identifying the problem such as **logs**, **screenshots**, **configuration dumps** etc.)

**Comment by nadouani** [comment]
@eliebilly what's the issue here?

**Comment by saadkadhi** [comment]
@eliebilly I am closing this as you basically kept the issue template and haven't stated any problem or feature request. Please avoid publishing this kind of useless content in the future.
