### ISSUE TITLE
Template's URL

### ISSUE THREAD

**Issue by ghost** [CERT-BDF/TheHive#92]
### Request Type
Question

### Problem Description
Hello,

I would like to put an Url link to the creation of an incident in theHive from a template. The problem is that there are not any ... This is just a pop up window that opens.

Is there a way to fix this?

Thank you

**Comment by nadouani** [comment]
Hi @CodyBr 

You mean, you want to have access to the case creation "page" (currently a popup window) by hitting a fixed/bookmarked URL?

**Comment by CodyBr** [comment]
Exactly !

**Comment by nadouani** [comment]
Well, as you said, this is not possible with the current version. We didn't think of this use case in fact. We can will consider this idea in the upcoming version.
