### ISSUE TITLE
Bug related case

### ISSUE THREAD

**Issue by commiaI** [CERT-BDF/TheHive#97]
### Request Type
Bug 

### Problem Description
I noticed a bug. When two observables are identical between two cases, there is a sentence indicating it to us. But when suppressed, there is nothing in common but the sentence indicating a related case remains.

**Comment by saadkadhi** [comment]
Hi @commiaI,

That's a good catch and we have already corrected it in Buckfast (v 2.10) which will be released in a few days.

Thanks.
