### ISSUE TITLE
Ldap authentication fails to take the good user

### ISSUE THREAD

**Issue by lanbus** [CERT-BDF/TheHive#98]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Windows
| TheHive version / git hash   | 2.9.1
| Package Type              | from Binary
| Browser type & version    | Mozilla or Chrome

### Problem Description
I Tried to use the LDAP authentication, but when it sends the request for the user, it doesn't use the username as a binding request. It just take one of the person of the group directing from the user.  Connection is good. If I put only a user in the filter it works. But only for this one. 

### Steps to Reproduce
Step 1 Configure LDAP
Step 2 Try to log in.

### Complementary information
none more.

**Comment by To-om** [comment]
In order to user LDAP authentication, you must specify a bind account in configuration (`bindDN` and `bindPW`). This account is used to search user DN according to `baseDN` and `filter` parameters.

When the user DN is found, an authentication is attempt using password provided by the user.

The configuration must looks like (cf. [Administration guide](https://github.com/CERT-BDF/TheHive/wiki/Administrator's-guide#44-authentication)):
```
auth {
    ldap {
        # LDAP server name or address. Port can be specified (host:port). This parameter is required.
        serverName = "ldap.mydomain.local:389"

        # Use SSL to connect to directory server
        #useSSL = true

        # Account to use to bind on LDAP server. This parameter is required.
        bindDN = "cn=thehive,ou=services,dc=mydomain,dc=local"

        # Password of the binding account. This parameter is required.
        bindPW = "***secret*password***"

        # Base DN to search users. This parameter is required.
        baseDN = "ou=users,dc=mydomain,dc=local"

        # Filter to search user {0} is replaced by user name. This parameter is required.
        filter = "(cn={0})"
    }
}
```

**Comment by lanbus** [comment]
Hello, 
Yes I have configured that. The first bind goes on smoothly. I put a group on my filter. But when I inspect the packets, I can see that it doesn't try the correct user from the group. Instead it take one of the user of the group and try with the password I provided.

**Comment by To-om** [comment]
What is your filter parameter ?

**Comment by lanbus** [comment]
(&(objectClass=user)(memberof=cn=hive_users,cn=Users,dc=MySubdomain,dc=MyDomain))

**Comment by To-om** [comment]
You did'nt integrate `{0}` in your filter. `{0}` is replaced by the user login. Your filter should looks like:
`(&(objectClass=user)(memberof=cn=hive_users,cn=Users,dc=MySubdomain,dc=MyDomain)(cn={0}))`

**Comment by lanbus** [comment]
Exact, I didn't get the syntax properly. It works fine now. Thanks a lot!
